In [1]:
# ONLY RUN THIS IF YOU'RE IN GOOGLE COLAB
from google.colab import drive
import os

drive.mount('/content/drive')
os.chdir('/content/drive/MyDrive/Thesis/Pintu-Air/notebooks')

# Verify you're in the right place
!pwd
!ls -la

Mounted at /content/drive
/content/drive/MyDrive/Thesis/Pintu-Air/notebooks
total 91871
-rw------- 1 root root  6303711 Dec 28 17:51  01_Result_Data_Cleaning_Part1.csv
-rw------- 1 root root  1720705 Dec 28 17:51  02_Data_Preperation.ipynb
-rw------- 1 root root  2300416 Dec 28 17:51  03_All_Data.csv
-rw------- 1 root root  1984161 Dec 28 17:51  04_X_test_all.csv
-rw------- 1 root root 37612340 Dec 28 17:51  04_X_train_all.csv
-rw------- 1 root root    46509 Dec 28 17:51  04_y_test.csv
-rw------- 1 root root   883281 Dec 28 17:51  04_y_train.csv
-rw------- 1 root root  1205202 Dec 28 17:51  05_X_test_binary.csv
-rw------- 1 root root 22929893 Dec 28 17:51  05_X_train_binary.csv
-rw------- 1 root root   584912 Dec 28 17:51  06_X_test_significant.csv
-rw------- 1 root root 11132982 Dec 28 17:51  06_X_train_significant.csv
-rw------- 1 root root    47887 Dec 28 17:51  11_XGBoost_all_GridSearch_Results.csv
-rw------- 1 root root  1532395 Dec 28 17:51  11_XGBoost_all.ipynb
-rw------- 1 root root    48004 Dec 28 17:51  12_XGBoost_binary_GridSearch_Results.csv
-rw------- 1 root root  1526560 Dec 28 17:51  12_XGBoost_binary.ipynb
-rw------- 1 root root    47879 Dec 28 17:51  13_XGBoost_significant_GridSearch_Results.csv
-rw------- 1 root root  1524267 Dec 28 17:51  13_XGBoost_significant.ipynb
-rw------- 1 root root  1439004 Dec 28 17:51  21_ARIMA.ipynb
-rw------- 1 root root    65104 Dec 28 17:51  22_arima_results.csv
-rw------- 1 root root     2831 Dec 28 17:51  23_arima_results_all_significant.csv
-rw------- 1 root root   366310 Jan  6 11:22  31_LSTM_all.ipynb
-rw------- 1 root root     7887 Dec 28 21:37  31_LSTM_all_Results2.csv
-rw------- 1 root root     9382 Dec 29 21:18  31_LSTM_all_Results3.csv
-rw------- 1 root root     7033 Dec 30 00:50  31_LSTM_all_Results4.csv
-rw------- 1 root root    11810 Dec 28 17:51  31_LSTM_all_Results.csv
drwx------ 2 root root     4096 Dec 28 17:51  31_saved_plots
-rw------- 1 root root   314038 Dec 28 17:51  32_LSTM_binary.ipynb
-rw------- 1 root root    11819 Dec 28 17:51  32_LSTM_binary_Results.csv
drwx------ 2 root root     4096 Dec 28 17:51  32_saved_plots
-rw------- 1 root root   373695 Dec 28 17:51  33_LSTM_significant.ipynb
-rw------- 1 root root    11818 Dec 28 17:51  33_LSTM_significant_Results.csv
drwx------ 2 root root     4096 Dec 28 17:51  33_saved_plots
drwx------ 2 root root     4096 Dec 28 19:16 'saved plots'

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_absolute_percentage_error
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import RobustScaler
from itertools import product
import os
import warnings
import time
warnings.filterwarnings('ignore')

In [3]:
# GPU Configuration
print("GPU Available:", tf.config.list_physical_devices('GPU'))

# ADD THIS BLOCK:
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print("GPU memory growth enabled")
    except RuntimeError as e:
        print(f"GPU setup error: {e}")

GPU Available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
GPU memory growth enabled

In [4]:
# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

In [5]:
y_train = (pd.read_csv("04_y_train.csv", index_col='Tanggal')).values
y_test = (pd.read_csv("04_y_test.csv", index_col='Tanggal')).values

In [6]:
X = pd.read_csv("03_All_Data.csv")
X['Tanggal'] = pd.to_datetime(X['Tanggal'])
X = X.set_index('Tanggal').iloc[24:]
X.columns = (
    X.columns
    .str.replace(r'\s*\((.*?)\)', r'_\1', regex=True)
    .str.lower()
)
X

,katulampa_air,katulampa_cuaca,depok_air,depok_cuaca,manggarai_air,manggarai_cuaca
Tanggal,,,,,,
2021-10-17 00:00:00,20.0,Mendung,80.0,Mendung Tipis,590.0,Terang
2021-10-17 01:00:00,20.0,Mendung Tipis,80.0,Mendung Tipis,575.0,Terang
2021-10-17 02:00:00,10.0,Mendung Tipis,80.0,Mendung Tipis,570.0,Terang
2021-10-17 03:00:00,10.0,Mendung Tipis,80.0,Mendung Tipis,565.0,Terang
2021-10-17 04:00:00,10.0,Mendung Tipis,80.0,Mendung Tipis,560.0,Terang
...,...,...,...,...,...,...
2025-11-14 19:00:00,30.0,Mendung,90.0,Mendung Tipis,660.0,Mendung
2025-11-14 20:00:00,30.0,Mendung,90.0,Mendung Tipis,660.0,Mendung
2025-11-14 21:00:00,30.0,Mendung,90.0,Mendung Tipis,660.0,Mendung
2025-11-14 22:00:00,30.0,Mendung,90.0,Mendung Tipis,660.0,Mendung
2025-11-14 23:00:00,30.0,Mendung,90.0,Mendung Tipis,660.0,Mendung

In [7]:
# Feature Processing
categorical_cols = [col for col in X.columns if 'cuaca' in col]
numeric_cols = [col for col in X.columns if 'air' in col]

X_num = X[numeric_cols].copy()
X_cat = pd.DataFrame()

for col in categorical_cols:
    # Create one-hot encoding for this cuaca column
    dummies = pd.get_dummies(X[col], prefix=col, drop_first=False, dtype=int)

    # Drop 'Terang' column if it exists
    terang_col = f'{col}_Terang'
    if terang_col in dummies.columns:
        dummies = dummies.drop(terang_col, axis=1)

    # Add dummy columns to dataframe
    X_cat = pd.concat([X_cat, dummies], axis=1)

In [8]:
X_cat

,katulampa_cuaca_Gerimis,katulampa_cuaca_Hujan,katulampa_cuaca_Mendung,katulampa_cuaca_Mendung Tipis,depok_cuaca_Gerimis,depok_cuaca_Hujan,depok_cuaca_Mendung,depok_cuaca_Mendung Tipis,manggarai_cuaca_Gerimis,manggarai_cuaca_Hujan,manggarai_cuaca_Mendung,manggarai_cuaca_Mendung Tipis
Tanggal,,,,,,,,,,,,
2021-10-17 00:00:00,0,0,1,0,0,0,0,1,0,0,0,0
2021-10-17 01:00:00,0,0,0,1,0,0,0,1,0,0,0,0
2021-10-17 02:00:00,0,0,0,1,0,0,0,1,0,0,0,0
2021-10-17 03:00:00,0,0,0,1,0,0,0,1,0,0,0,0
2021-10-17 04:00:00,0,0,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2025-11-14 19:00:00,0,0,1,0,0,0,0,1,0,0,1,0
2025-11-14 20:00:00,0,0,1,0,0,0,0,1,0,0,1,0
2025-11-14 21:00:00,0,0,1,0,0,0,0,1,0,0,1,0
2025-11-14 22:00:00,0,0,1,0,0,0,0,1,0,0,1,0
2025-11-14 23:00:00,0,0,1,0,0,0,0,1,0,0,1,0

In [9]:
# Train-Test Split
split_idx = int(len(X) * 0.95)
X_num_train, X_num_test = X_num[:split_idx], X_num[split_idx:]
X_cat_train, X_cat_test = X_cat[:split_idx], X_cat[split_idx:]

# Scaling
# scaler_X = MinMaxScaler()
# scaler_y = MinMaxScaler()
scaler_X = RobustScaler()
scaler_y = RobustScaler()

X_num_train_scaled = scaler_X.fit_transform(X_num_train)
X_num_test_scaled = scaler_X.transform(X_num_test)
y_train_scaled = scaler_y.fit_transform(y_train.reshape(-1, 1)).flatten()


print(f"\n{'='*60}\nData Train and Test Distribution:\n{'='*60}")

print(f'Jumlah data: {len(X)}')

print(f'Jumlah data X train: {len(X_num_train)}')
print(f'Jumlah data X test: {len(X_num_test)}')

print(f'Jumlah data y train: {len(y_train)}')
print(f'Jumlah data y test: {len(y_test)}')

============================================================
Data Train and Test Distribution:
============================================================
Jumlah data: 35760
Jumlah data X train: 33972
Jumlah data X test: 1788
Jumlah data y train: 33972
Jumlah data y test: 1788

In [10]:
# Combine Features
X_train = np.concatenate([X_num_train_scaled, X_cat_train.values], axis=1)
X_test = np.concatenate([X_num_test_scaled, X_cat_test.values], axis=1)

print(f"Features: {X_train.shape[1]} total ({len(numeric_cols)} numeric, {len(categorical_cols)} categorical)")

Features: 15 total (3 numeric, 3 categorical)

In [11]:
def create_sequences(X, y, seq_len):
    X_seq, y_seq = [], []

    for i in range(seq_len, len(X)):
        # Take seq_len previous time steps as features
        X_seq.append(X[i-seq_len:i])
        # Current time step as target
        y_seq.append(y[i])

    return np.array(X_seq), np.array(y_seq)

In [12]:
def build_model(seq_len, n_features, units, dropout, lr):
    model = Sequential()
    for i, unit in enumerate(units):
        return_seq = i < len(units) - 1
        if i == 0:
            model.add(LSTM(unit, return_sequences=return_seq, input_shape=(seq_len, n_features)))
        else:
            model.add(LSTM(unit, return_sequences=return_seq))
        model.add(Dropout(dropout))
    model.add(Dense(16, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer=Adam(learning_rate=lr), loss='mse', metrics=['mae'])
    return model

In [13]:
def evaluate_model(model, X_seq, y_true, scaler_y):
    y_pred_scaled = model.predict(X_seq, verbose=0)
    y_pred = scaler_y.inverse_transform(y_pred_scaled.reshape(-1, 1)).flatten()

    # Calculate metrics
    return {
        'rmse': np.sqrt(mean_squared_error(y_true, y_pred)),
        'mae': mean_absolute_error(y_true, y_pred),
        'r2': r2_score(y_true, y_pred),
        'mape': mean_absolute_percentage_error(y_true, y_pred)
    }

In [14]:
def save_learning_curves(history, combo_id, params):
    os.makedirs('saved plots', exist_ok=True)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

    ax1.plot(history.history['loss'], label='Train')
    ax1.plot(history.history['val_loss'], label='Validation')
    ax1.set_title(f'Loss - Combo {combo_id}')
    ax1.set_ylabel('Loss')
    ax1.legend()
    ax1.grid(True)

    ax2.plot(history.history['mae'], label='Train')
    ax2.plot(history.history['val_mae'], label='Validation')
    ax2.set_title(f'MAE - Combo {combo_id}')
    ax2.set_ylabel('MAE')
    ax2.legend()
    ax2.grid(True)

    plt.tight_layout()
    # Handle list to string conversion for filename safely
    units_str = str(params['lstm_units']).replace('[','').replace(']','').replace(',','-')
    filename = f"LSTM_Combo{combo_id}_Seq{params['sequence_length']}_Unit{units_str}_Dr{params['dropout_rate']}.png"
    plt.savefig(f"31_saved_plots/{filename}", dpi=100, bbox_inches='tight')
    plt.close()

In [15]:
def lstm_grid_search(X_train, y_train_scaled, X_test, y_test, scaler_y, param_grid, run_id):
    param_combinations = list(product(*param_grid.values()))
    param_names = list(param_grid.keys())
    total_combinations = len(param_combinations)

    print(f"Starting grid search: {total_combinations} combinations")
    results = []

    for i, params in enumerate(param_combinations):
        param_dict = dict(zip(param_names, params))
        print(f"\nCombination {i+1}/{total_combinations}: {param_dict}")

        try:
            # 1. Create Sequences
            X_seq, y_seq = create_sequences(X_train, y_train_scaled, param_dict['sequence_length'])

            # Validation Split (20%)
            val_size = int(len(X_seq) * 0.2)
            X_train_fold = X_seq[:-val_size]
            y_train_fold = y_seq[:-val_size]
            X_val_fold = X_seq[-val_size:]
            y_val_fold = y_seq[-val_size:]

            # 2. Build Model
            model = build_model(
                param_dict['sequence_length'],
                X_seq.shape[2],
                param_dict['lstm_units'],
                param_dict['dropout_rate'],
                param_dict['learning_rate']
            )

            callbacks = [
                EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, min_delta=0.0001),
                ReduceLROnPlateau(monitor='val_loss', factor=0.3, patience=3, min_lr=0.00001)
            ]

            # 3. Train with Timer
            start_time = time.time() # Start Timer

            history = model.fit(
                X_train_fold, y_train_fold,
                epochs=param_dict['epochs'],
                batch_size=param_dict['batch_size'],
                validation_data=(X_val_fold, y_val_fold),
                callbacks=callbacks,
                verbose=0 # Silent training to keep output clean
            )

            training_time = time.time() - start_time # End Timer

            # Save Plot
            save_learning_curves(history, i+1, param_dict)

            # 4. Evaluate (Train & Test)
            # Train Set (Using the fold used for training to see fit)
            y_train_fold_orig = scaler_y.inverse_transform(y_train_fold.reshape(-1, 1)).flatten()
            train_metrics = evaluate_model(model, X_train_fold, y_train_fold_orig, scaler_y)

            # Test Set
            X_test_seq, _ = create_sequences(X_test, y_test.flatten(), param_dict['sequence_length'])
            y_test_actual = y_test[param_dict['sequence_length']:]
            test_metrics = evaluate_model(model, X_test_seq, y_test_actual, scaler_y)

            # 5. Format Result for CSV
            result_entry = {
                'Seq': param_dict['sequence_length'],
                'Unit': str(param_dict['lstm_units']), # Convert list to string for CSV
                'Dropout': param_dict['dropout_rate'],
                'LR': param_dict['learning_rate'],
                'Batch Size': param_dict['batch_size'],
                'Epoch': len(history.history['loss']), # Actual epochs run

                'training_time_sec': round(training_time, 8),

                'train_rmse': round(train_metrics['rmse'], 8),
                'train_mae': round(train_metrics['mae'], 8),
                'train_mape': round(train_metrics['mape'], 8),
                'train_r2': round(train_metrics['r2'], 8),

                'test_rmse': round(test_metrics['rmse'], 8),
                'test_mae': round(test_metrics['mae'], 8),
                'test_mape': round(test_metrics['mape'], 8),
                'test_r2': round(test_metrics['r2'], 8)
            }
            results.append(result_entry)

            print(f"   -> Time: {training_time:.2f}s | Train RMSE: {train_metrics['rmse']:.4f} | Test RMSE: {test_metrics['rmse']:.4f}")
            df_results = pd.DataFrame(results)
            df_results.to_csv(f'31_LSTM_all_Results{run_id}.csv', index=False)

        except Exception as e:
            print(f"Error in combination {i+1}: {str(e)}")
            # Append error row to keep track
            results.append({'Seq': param_dict['sequence_length'], 'test_rmse': 999999, 'error': str(e)})
            df_results = pd.DataFrame(results)
            df_results.to_csv(f'31_LSTM_all_Results{run_id}.csv', index=False)

    return pd.DataFrame(results)

In [16]:
param_grid = {
    'sequence_length': [12, 24, 36],
    'lstm_units': [
        [16,8],
        [128],
        [32,16],
        [64],
        [64,32]
    ],
    'dropout_rate': [0.4, 0.2],
    'learning_rate': [0.0001, 0.0005, 0.002],
    'batch_size': [32],
    'epochs': [40]
}

In [ ]:
df_results = lstm_grid_search(X_train, y_train_scaled, X_test, y_test, scaler_y, param_grid)

Starting grid search: 90 combinations

Combination 1/90: {'sequence_length': 12, 'lstm_units': [16, 8], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 259.70s | Train RMSE: 18.7172 | Test RMSE: 15.6753

Combination 2/90: {'sequence_length': 12, 'lstm_units': [16, 8], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 95.76s | Train RMSE: 18.1169 | Test RMSE: 15.3414

Combination 3/90: {'sequence_length': 12, 'lstm_units': [16, 8], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 37.81s | Train RMSE: 20.6046 | Test RMSE: 18.5472

Combination 4/90: {'sequence_length': 12, 'lstm_units': [16, 8], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 251.59s | Train RMSE: 17.1902 | Test RMSE: 15.3459

Combination 5/90: {'sequence_length': 12, 'lstm_units': [16, 8], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 112.76s | Train RMSE: 16.9825 | Test RMSE: 15.2205

Combination 6/90: {'sequence_length': 12, 'lstm_units': [16, 8], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 86.93s | Train RMSE: 16.7201 | Test RMSE: 14.9390

Combination 7/90: {'sequence_length': 12, 'lstm_units': [128], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 125.37s | Train RMSE: 16.4295 | Test RMSE: 15.1590

Combination 8/90: {'sequence_length': 12, 'lstm_units': [128], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 58.80s | Train RMSE: 16.7100 | Test RMSE: 15.1404

Combination 9/90: {'sequence_length': 12, 'lstm_units': [128], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 53.26s | Train RMSE: 16.3906 | Test RMSE: 14.9941

Combination 10/90: {'sequence_length': 12, 'lstm_units': [128], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 97.48s | Train RMSE: 16.5104 | Test RMSE: 15.3521

Combination 11/90: {'sequence_length': 12, 'lstm_units': [128], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 81.63s | Train RMSE: 16.1675 | Test RMSE: 15.2237

Combination 12/90: {'sequence_length': 12, 'lstm_units': [128], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 56.35s | Train RMSE: 16.1632 | Test RMSE: 14.9833

Combination 13/90: {'sequence_length': 12, 'lstm_units': [32, 16], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 237.43s | Train RMSE: 19.2748 | Test RMSE: 15.6318

Combination 14/90: {'sequence_length': 12, 'lstm_units': [32, 16], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 85.36s | Train RMSE: 17.3991 | Test RMSE: 15.1064

Combination 15/90: {'sequence_length': 12, 'lstm_units': [32, 16], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 45.90s | Train RMSE: 18.6022 | Test RMSE: 15.9874

Combination 16/90: {'sequence_length': 12, 'lstm_units': [32, 16], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 199.19s | Train RMSE: 16.6141 | Test RMSE: 15.3737

Combination 17/90: {'sequence_length': 12, 'lstm_units': [32, 16], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 97.61s | Train RMSE: 16.6060 | Test RMSE: 15.0195

Combination 18/90: {'sequence_length': 12, 'lstm_units': [32, 16], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 82.43s | Train RMSE: 16.2989 | Test RMSE: 15.1289

Combination 19/90: {'sequence_length': 12, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 191.12s | Train RMSE: 16.3876 | Test RMSE: 15.3131

Combination 20/90: {'sequence_length': 12, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 51.48s | Train RMSE: 16.4682 | Test RMSE: 15.1291

Combination 21/90: {'sequence_length': 12, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 83.48s | Train RMSE: 16.1463 | Test RMSE: 15.0348

Combination 22/90: {'sequence_length': 12, 'lstm_units': [64], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 110.96s | Train RMSE: 16.4828 | Test RMSE: 15.3205

Combination 23/90: {'sequence_length': 12, 'lstm_units': [64], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 83.00s | Train RMSE: 16.2160 | Test RMSE: 15.1408

Combination 24/90: {'sequence_length': 12, 'lstm_units': [64], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 80.51s | Train RMSE: 16.1934 | Test RMSE: 15.0401

Combination 25/90: {'sequence_length': 12, 'lstm_units': [64, 32], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 237.92s | Train RMSE: 16.6278 | Test RMSE: 15.1853

Combination 26/90: {'sequence_length': 12, 'lstm_units': [64, 32], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 96.33s | Train RMSE: 16.8122 | Test RMSE: 15.0565

Combination 27/90: {'sequence_length': 12, 'lstm_units': [64, 32], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 54.17s | Train RMSE: 16.8018 | Test RMSE: 15.0563

Combination 28/90: {'sequence_length': 12, 'lstm_units': [64, 32], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 212.24s | Train RMSE: 16.4869 | Test RMSE: 15.2909

Combination 29/90: {'sequence_length': 12, 'lstm_units': [64, 32], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 167.32s | Train RMSE: 16.0504 | Test RMSE: 15.0679

Combination 30/90: {'sequence_length': 12, 'lstm_units': [64, 32], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 48.99s | Train RMSE: 16.8929 | Test RMSE: 15.0690

Combination 31/90: {'sequence_length': 24, 'lstm_units': [16, 8], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 297.16s | Train RMSE: 19.9475 | Test RMSE: 15.5453

Combination 32/90: {'sequence_length': 24, 'lstm_units': [16, 8], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 75.28s | Train RMSE: 19.2532 | Test RMSE: 16.4404

Combination 33/90: {'sequence_length': 24, 'lstm_units': [16, 8], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 120.85s | Train RMSE: 20.1567 | Test RMSE: 16.1118

Combination 34/90: {'sequence_length': 24, 'lstm_units': [16, 8], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 303.76s | Train RMSE: 17.0219 | Test RMSE: 15.4548

Combination 35/90: {'sequence_length': 24, 'lstm_units': [16, 8], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 135.99s | Train RMSE: 17.0602 | Test RMSE: 15.7514

Combination 36/90: {'sequence_length': 24, 'lstm_units': [16, 8], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 93.08s | Train RMSE: 16.7313 | Test RMSE: 15.5440

Combination 37/90: {'sequence_length': 24, 'lstm_units': [128], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 166.06s | Train RMSE: 16.3635 | Test RMSE: 15.7928

Combination 38/90: {'sequence_length': 24, 'lstm_units': [128], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 75.30s | Train RMSE: 16.4646 | Test RMSE: 15.3677

Combination 39/90: {'sequence_length': 24, 'lstm_units': [128], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 79.88s | Train RMSE: 16.2433 | Test RMSE: 15.2820

Combination 40/90: {'sequence_length': 24, 'lstm_units': [128], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 113.38s | Train RMSE: 16.3040 | Test RMSE: 15.7037

Combination 41/90: {'sequence_length': 24, 'lstm_units': [128], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 119.83s | Train RMSE: 16.0052 | Test RMSE: 15.1971

Combination 42/90: {'sequence_length': 24, 'lstm_units': [128], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 97.62s | Train RMSE: 15.8193 | Test RMSE: 15.2059

Combination 43/90: {'sequence_length': 24, 'lstm_units': [32, 16], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 199.07s | Train RMSE: 17.2884 | Test RMSE: 16.1070

Combination 44/90: {'sequence_length': 24, 'lstm_units': [32, 16], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 169.72s | Train RMSE: 17.8744 | Test RMSE: 15.6724

Combination 45/90: {'sequence_length': 24, 'lstm_units': [32, 16], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 61.27s | Train RMSE: 18.3849 | Test RMSE: 15.9916

Combination 46/90: {'sequence_length': 24, 'lstm_units': [32, 16], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 243.34s | Train RMSE: 16.8802 | Test RMSE: 15.9383

Combination 47/90: {'sequence_length': 24, 'lstm_units': [32, 16], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 137.16s | Train RMSE: 16.7157 | Test RMSE: 15.3423

Combination 48/90: {'sequence_length': 24, 'lstm_units': [32, 16], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 111.81s | Train RMSE: 16.8938 | Test RMSE: 15.1231

Combination 49/90: {'sequence_length': 24, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 176.78s | Train RMSE: 16.5842 | Test RMSE: 15.5474

Combination 50/90: {'sequence_length': 24, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 87.09s | Train RMSE: 16.5277 | Test RMSE: 15.4336

Combination 51/90: {'sequence_length': 24, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 82.33s | Train RMSE: 16.1607 | Test RMSE: 15.2371

Combination 52/90: {'sequence_length': 24, 'lstm_units': [64], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 214.28s | Train RMSE: 16.3327 | Test RMSE: 15.7447

Combination 53/90: {'sequence_length': 24, 'lstm_units': [64], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 90.97s | Train RMSE: 16.2726 | Test RMSE: 15.3871

Combination 54/90: {'sequence_length': 24, 'lstm_units': [64], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 92.69s | Train RMSE: 16.0256 | Test RMSE: 15.1854

Combination 55/90: {'sequence_length': 24, 'lstm_units': [64, 32], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 297.60s | Train RMSE: 16.5707 | Test RMSE: 15.5753

Combination 56/90: {'sequence_length': 24, 'lstm_units': [64, 32], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 158.05s | Train RMSE: 16.3297 | Test RMSE: 15.3070

Combination 57/90: {'sequence_length': 24, 'lstm_units': [64, 32], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 111.59s | Train RMSE: 18.9161 | Test RMSE: 15.1202

Combination 58/90: {'sequence_length': 24, 'lstm_units': [64, 32], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 258.97s | Train RMSE: 16.3120 | Test RMSE: 15.6615

Combination 59/90: {'sequence_length': 24, 'lstm_units': [64, 32], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 134.25s | Train RMSE: 16.1639 | Test RMSE: 15.4794

Combination 60/90: {'sequence_length': 24, 'lstm_units': [64, 32], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 64.44s | Train RMSE: 17.0543 | Test RMSE: 15.1888

Combination 61/90: {'sequence_length': 36, 'lstm_units': [16, 8], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 199.14s | Train RMSE: 18.7827 | Test RMSE: 16.3209

Combination 62/90: {'sequence_length': 36, 'lstm_units': [16, 8], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 77.26s | Train RMSE: 18.7377 | Test RMSE: 16.3674

Combination 63/90: {'sequence_length': 36, 'lstm_units': [16, 8], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 55.15s | Train RMSE: 19.0614 | Test RMSE: 15.3454

Combination 64/90: {'sequence_length': 36, 'lstm_units': [16, 8], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 310.17s | Train RMSE: 16.6451 | Test RMSE: 15.6416

Combination 65/90: {'sequence_length': 36, 'lstm_units': [16, 8], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 147.00s | Train RMSE: 16.4308 | Test RMSE: 15.2669

Combination 66/90: {'sequence_length': 36, 'lstm_units': [16, 8], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 86.43s | Train RMSE: 16.8506 | Test RMSE: 15.0915

Combination 67/90: {'sequence_length': 36, 'lstm_units': [128], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 118.14s | Train RMSE: 16.0738 | Test RMSE: 15.6081

Combination 68/90: {'sequence_length': 36, 'lstm_units': [128], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 116.38s | Train RMSE: 15.7709 | Test RMSE: 15.4527

Combination 69/90: {'sequence_length': 36, 'lstm_units': [128], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 104.25s | Train RMSE: 15.6968 | Test RMSE: 15.2745

Combination 70/90: {'sequence_length': 36, 'lstm_units': [128], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 154.79s | Train RMSE: 15.8670 | Test RMSE: 15.8422

Combination 71/90: {'sequence_length': 36, 'lstm_units': [128], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 58.84s | Train RMSE: 15.9901 | Test RMSE: 15.4972

Combination 72/90: {'sequence_length': 36, 'lstm_units': [128], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 92.11s | Train RMSE: 15.7405 | Test RMSE: 15.4604

Combination 73/90: {'sequence_length': 36, 'lstm_units': [32, 16], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 275.51s | Train RMSE: 16.5585 | Test RMSE: 15.7177

Combination 74/90: {'sequence_length': 36, 'lstm_units': [32, 16], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 149.31s | Train RMSE: 18.8534 | Test RMSE: 15.2288

Combination 75/90: {'sequence_length': 36, 'lstm_units': [32, 16], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 55.15s | Train RMSE: 17.1789 | Test RMSE: 15.3679

Combination 76/90: {'sequence_length': 36, 'lstm_units': [32, 16], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 317.09s | Train RMSE: 16.1753 | Test RMSE: 15.6468

Combination 77/90: {'sequence_length': 36, 'lstm_units': [32, 16], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 120.92s | Train RMSE: 16.1407 | Test RMSE: 15.4553

Combination 78/90: {'sequence_length': 36, 'lstm_units': [32, 16], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 124.73s | Train RMSE: 16.2381 | Test RMSE: 15.2809

Combination 79/90: {'sequence_length': 36, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 246.07s | Train RMSE: 16.0100 | Test RMSE: 15.5283

Combination 80/90: {'sequence_length': 36, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 105.46s | Train RMSE: 16.0922 | Test RMSE: 15.5006

Combination 81/90: {'sequence_length': 36, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 79.19s | Train RMSE: 15.8791 | Test RMSE: 15.2625

Combination 82/90: {'sequence_length': 36, 'lstm_units': [64], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 177.20s | Train RMSE: 15.9323 | Test RMSE: 15.7054

Combination 83/90: {'sequence_length': 36, 'lstm_units': [64], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 92.32s | Train RMSE: 15.8223 | Test RMSE: 15.4488

Combination 84/90: {'sequence_length': 36, 'lstm_units': [64], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 40.65s | Train RMSE: 16.1609 | Test RMSE: 15.2385

Combination 85/90: {'sequence_length': 36, 'lstm_units': [64, 32], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 289.18s | Train RMSE: 16.2713 | Test RMSE: 15.7396

Combination 86/90: {'sequence_length': 36, 'lstm_units': [64, 32], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 140.39s | Train RMSE: 17.1763 | Test RMSE: 15.5984

Combination 87/90: {'sequence_length': 36, 'lstm_units': [64, 32], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 78.39s | Train RMSE: 16.9639 | Test RMSE: 15.2683

Combination 88/90: {'sequence_length': 36, 'lstm_units': [64, 32], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 275.30s | Train RMSE: 16.0891 | Test RMSE: 15.6381

Combination 89/90: {'sequence_length': 36, 'lstm_units': [64, 32], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 108.68s | Train RMSE: 15.9192 | Test RMSE: 15.3893

Combination 90/90: {'sequence_length': 36, 'lstm_units': [64, 32], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 134.77s | Train RMSE: 15.7806 | Test RMSE: 15.3843

In [ ]:
param_grid = {
    'sequence_length': [6, 48],
    'lstm_units': [
        [16,8],
        [128],
        [32,16],
        [64],
        [64,32]
    ],
    'dropout_rate': [0.4, 0.2],
    'learning_rate': [0.0001, 0.0005, 0.002],
    'batch_size': [32],
    'epochs': [40]
}

In [ ]:
df_results = lstm_grid_search(X_train, y_train_scaled, X_test, y_test, scaler_y, param_grid, 2)

Starting grid search: 60 combinations

Combination 1/60: {'sequence_length': 6, 'lstm_units': [16, 8], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 273.30s | Train RMSE: 18.8660 | Test RMSE: 15.8450

Combination 2/60: {'sequence_length': 6, 'lstm_units': [16, 8], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 61.18s | Train RMSE: 18.2940 | Test RMSE: 16.0813

Combination 3/60: {'sequence_length': 6, 'lstm_units': [16, 8], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 41.25s | Train RMSE: 18.6941 | Test RMSE: 15.5844

Combination 4/60: {'sequence_length': 6, 'lstm_units': [16, 8], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 198.04s | Train RMSE: 17.2387 | Test RMSE: 15.6282

Combination 5/60: {'sequence_length': 6, 'lstm_units': [16, 8], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 117.66s | Train RMSE: 16.8213 | Test RMSE: 15.4103

Combination 6/60: {'sequence_length': 6, 'lstm_units': [16, 8], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 48.43s | Train RMSE: 16.8851 | Test RMSE: 15.1357

Combination 7/60: {'sequence_length': 6, 'lstm_units': [128], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 204.11s | Train RMSE: 16.3885 | Test RMSE: 15.3762

Combination 8/60: {'sequence_length': 6, 'lstm_units': [128], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 67.77s | Train RMSE: 16.4678 | Test RMSE: 15.3135

Combination 9/60: {'sequence_length': 6, 'lstm_units': [128], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 76.35s | Train RMSE: 16.2276 | Test RMSE: 14.9899

Combination 10/60: {'sequence_length': 6, 'lstm_units': [128], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 123.33s | Train RMSE: 16.4396 | Test RMSE: 15.5207

Combination 11/60: {'sequence_length': 6, 'lstm_units': [128], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 57.59s | Train RMSE: 16.4068 | Test RMSE: 15.1877

Combination 12/60: {'sequence_length': 6, 'lstm_units': [128], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 75.84s | Train RMSE: 16.0557 | Test RMSE: 15.0499

Combination 13/60: {'sequence_length': 6, 'lstm_units': [32, 16], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 247.50s | Train RMSE: 17.5258 | Test RMSE: 15.4012

Combination 14/60: {'sequence_length': 6, 'lstm_units': [32, 16], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 134.62s | Train RMSE: 18.1376 | Test RMSE: 15.1946

Combination 15/60: {'sequence_length': 6, 'lstm_units': [32, 16], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 54.02s | Train RMSE: 17.9211 | Test RMSE: 15.4055

Combination 16/60: {'sequence_length': 6, 'lstm_units': [32, 16], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 261.69s | Train RMSE: 16.5448 | Test RMSE: 15.2811

Combination 17/60: {'sequence_length': 6, 'lstm_units': [32, 16], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 98.31s | Train RMSE: 16.6445 | Test RMSE: 15.2509

Combination 18/60: {'sequence_length': 6, 'lstm_units': [32, 16], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 75.29s | Train RMSE: 16.7945 | Test RMSE: 15.0105

Combination 19/60: {'sequence_length': 6, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 211.20s | Train RMSE: 16.4811 | Test RMSE: 15.5111

Combination 20/60: {'sequence_length': 6, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 126.99s | Train RMSE: 16.3695 | Test RMSE: 15.2221

Combination 21/60: {'sequence_length': 6, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 66.36s | Train RMSE: 16.3771 | Test RMSE: 15.1379

Combination 22/60: {'sequence_length': 6, 'lstm_units': [64], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 172.78s | Train RMSE: 16.4975 | Test RMSE: 15.5476

Combination 23/60: {'sequence_length': 6, 'lstm_units': [64], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 86.02s | Train RMSE: 16.3966 | Test RMSE: 15.1633

Combination 24/60: {'sequence_length': 6, 'lstm_units': [64], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 72.97s | Train RMSE: 16.2517 | Test RMSE: 15.0357

Combination 25/60: {'sequence_length': 6, 'lstm_units': [64, 32], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 210.22s | Train RMSE: 16.9092 | Test RMSE: 15.8756

Combination 26/60: {'sequence_length': 6, 'lstm_units': [64, 32], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 125.98s | Train RMSE: 16.5353 | Test RMSE: 15.1683

Combination 27/60: {'sequence_length': 6, 'lstm_units': [64, 32], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 130.11s | Train RMSE: 16.8644 | Test RMSE: 15.0127

Combination 28/60: {'sequence_length': 6, 'lstm_units': [64, 32], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 219.37s | Train RMSE: 16.4841 | Test RMSE: 15.4253

Combination 29/60: {'sequence_length': 6, 'lstm_units': [64, 32], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 127.86s | Train RMSE: 16.3223 | Test RMSE: 15.1410

Combination 30/60: {'sequence_length': 6, 'lstm_units': [64, 32], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 90.62s | Train RMSE: 16.5283 | Test RMSE: 15.0583

Combination 31/60: {'sequence_length': 48, 'lstm_units': [16, 8], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 329.76s | Train RMSE: 18.6978 | Test RMSE: 15.9712

Combination 32/60: {'sequence_length': 48, 'lstm_units': [16, 8], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 101.23s | Train RMSE: 18.0043 | Test RMSE: 16.2740

Combination 33/60: {'sequence_length': 48, 'lstm_units': [16, 8], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 88.89s | Train RMSE: 19.2915 | Test RMSE: 15.1850

Combination 34/60: {'sequence_length': 48, 'lstm_units': [16, 8], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 339.85s | Train RMSE: 16.6235 | Test RMSE: 15.5092

Combination 35/60: {'sequence_length': 48, 'lstm_units': [16, 8], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 138.78s | Train RMSE: 16.4689 | Test RMSE: 15.3292

Combination 36/60: {'sequence_length': 48, 'lstm_units': [16, 8], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 80.97s | Train RMSE: 16.6301 | Test RMSE: 15.4076

Combination 37/60: {'sequence_length': 48, 'lstm_units': [128], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 141.44s | Train RMSE: 16.0669 | Test RMSE: 15.8549

Combination 38/60: {'sequence_length': 48, 'lstm_units': [128], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 100.81s | Train RMSE: 15.8660 | Test RMSE: 15.3890

Combination 39/60: {'sequence_length': 48, 'lstm_units': [128], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 89.42s | Train RMSE: 15.7259 | Test RMSE: 15.2507

Combination 40/60: {'sequence_length': 48, 'lstm_units': [128], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 148.99s | Train RMSE: 15.8767 | Test RMSE: 15.8220

Combination 41/60: {'sequence_length': 48, 'lstm_units': [128], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 116.65s | Train RMSE: 15.6357 | Test RMSE: 15.4553

Combination 42/60: {'sequence_length': 48, 'lstm_units': [128], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 62.66s | Train RMSE: 15.8537 | Test RMSE: 15.3073

Combination 43/60: {'sequence_length': 48, 'lstm_units': [32, 16], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 337.59s | Train RMSE: 16.9341 | Test RMSE: 15.8924

Combination 44/60: {'sequence_length': 48, 'lstm_units': [32, 16], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 124.02s | Train RMSE: 17.6102 | Test RMSE: 15.4639

Combination 45/60: {'sequence_length': 48, 'lstm_units': [32, 16], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 66.69s | Train RMSE: 16.9807 | Test RMSE: 15.4996

Combination 46/60: {'sequence_length': 48, 'lstm_units': [32, 16], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 290.95s | Train RMSE: 16.3405 | Test RMSE: 15.7103

Combination 47/60: {'sequence_length': 48, 'lstm_units': [32, 16], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 166.37s | Train RMSE: 16.1042 | Test RMSE: 15.5080

Combination 48/60: {'sequence_length': 48, 'lstm_units': [32, 16], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 131.50s | Train RMSE: 16.7232 | Test RMSE: 15.3112

Combination 49/60: {'sequence_length': 48, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 149.87s | Train RMSE: 16.2690 | Test RMSE: 15.7255

Combination 50/60: {'sequence_length': 48, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 80.51s | Train RMSE: 16.0214 | Test RMSE: 15.4530

Combination 51/60: {'sequence_length': 48, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 59.01s | Train RMSE: 16.0498 | Test RMSE: 15.2325

Combination 52/60: {'sequence_length': 48, 'lstm_units': [64], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 175.15s | Train RMSE: 15.9420 | Test RMSE: 15.6643

Combination 53/60: {'sequence_length': 48, 'lstm_units': [64], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 133.77s | Train RMSE: 15.6469 | Test RMSE: 15.5420

Combination 54/60: {'sequence_length': 48, 'lstm_units': [64], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 100.11s | Train RMSE: 15.6493 | Test RMSE: 15.3386

Combination 55/60: {'sequence_length': 48, 'lstm_units': [64, 32], 'dropout_rate': 0.4, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 180.65s | Train RMSE: 16.5850 | Test RMSE: 16.0372

Combination 56/60: {'sequence_length': 48, 'lstm_units': [64, 32], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 170.58s | Train RMSE: 16.2957 | Test RMSE: 15.4222

Combination 57/60: {'sequence_length': 48, 'lstm_units': [64, 32], 'dropout_rate': 0.4, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 104.83s | Train RMSE: 15.9477 | Test RMSE: 15.2939

Combination 58/60: {'sequence_length': 48, 'lstm_units': [64, 32], 'dropout_rate': 0.2, 'learning_rate': 0.0001, 'batch_size': 32, 'epochs': 40}
   -> Time: 328.05s | Train RMSE: 16.1254 | Test RMSE: 15.6275

Combination 59/60: {'sequence_length': 48, 'lstm_units': [64, 32], 'dropout_rate': 0.2, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
   -> Time: 144.68s | Train RMSE: 16.1164 | Test RMSE: 15.5025

Combination 60/60: {'sequence_length': 48, 'lstm_units': [64, 32], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 157.69s | Train RMSE: 16.0838 | Test RMSE: 15.2934

In [ ]:
from google.colab import runtime
runtime.unassign()

In [ ]:
param_grid = {
    'sequence_length': [6, 12, 24],
    'lstm_units': [
        [8, 4],
        [16,8],
        [128],
        [32,16],
        [64],
        [64,32]
    ],
    'dropout_rate': [0.6, 0.1],
    'learning_rate': [0.002, 0.004],
    'batch_size': [32],
    'epochs': [40]
}

In [ ]:
df_results = lstm_grid_search(X_train, y_train_scaled, X_test, y_test, scaler_y, param_grid, 3)

Starting grid search: 72 combinations

Combination 1/72: {'sequence_length': 6, 'lstm_units': [8, 4], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 64.80s | Train RMSE: 21.2737 | Test RMSE: 16.4881

Combination 2/72: {'sequence_length': 6, 'lstm_units': [8, 4], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 40.43s | Train RMSE: 20.2706 | Test RMSE: 15.5858

Combination 3/72: {'sequence_length': 6, 'lstm_units': [8, 4], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 103.54s | Train RMSE: 16.4628 | Test RMSE: 15.1488

Combination 4/72: {'sequence_length': 6, 'lstm_units': [8, 4], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 76.61s | Train RMSE: 16.4432 | Test RMSE: 15.1372

Combination 5/72: {'sequence_length': 6, 'lstm_units': [16, 8], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 52.28s | Train RMSE: 18.6848 | Test RMSE: 15.2436

Combination 6/72: {'sequence_length': 6, 'lstm_units': [16, 8], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 39.26s | Train RMSE: 22.2595 | Test RMSE: 17.2039

Combination 7/72: {'sequence_length': 6, 'lstm_units': [16, 8], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 92.07s | Train RMSE: 16.3305 | Test RMSE: 15.0162

Combination 8/72: {'sequence_length': 6, 'lstm_units': [16, 8], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 94.83s | Train RMSE: 16.4356 | Test RMSE: 14.9337

Combination 9/72: {'sequence_length': 6, 'lstm_units': [128], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 80.90s | Train RMSE: 16.3170 | Test RMSE: 15.1540

Combination 10/72: {'sequence_length': 6, 'lstm_units': [128], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 84.12s | Train RMSE: 16.1691 | Test RMSE: 15.2231

Combination 11/72: {'sequence_length': 6, 'lstm_units': [128], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 75.08s | Train RMSE: 15.9778 | Test RMSE: 15.1121

Combination 12/72: {'sequence_length': 6, 'lstm_units': [128], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 65.78s | Train RMSE: 16.1723 | Test RMSE: 14.9207

Combination 13/72: {'sequence_length': 6, 'lstm_units': [32, 16], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 43.83s | Train RMSE: 18.7310 | Test RMSE: 16.4587

Combination 14/72: {'sequence_length': 6, 'lstm_units': [32, 16], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 42.50s | Train RMSE: 19.3511 | Test RMSE: 15.4305

Combination 15/72: {'sequence_length': 6, 'lstm_units': [32, 16], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 113.91s | Train RMSE: 16.3608 | Test RMSE: 15.0521

Combination 16/72: {'sequence_length': 6, 'lstm_units': [32, 16], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 97.50s | Train RMSE: 16.2407 | Test RMSE: 15.0399

Combination 17/72: {'sequence_length': 6, 'lstm_units': [64], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 69.17s | Train RMSE: 16.5830 | Test RMSE: 15.0880

Combination 18/72: {'sequence_length': 6, 'lstm_units': [64], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 88.54s | Train RMSE: 19.9217 | Test RMSE: 14.9999

Combination 19/72: {'sequence_length': 6, 'lstm_units': [64], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 77.76s | Train RMSE: 16.0731 | Test RMSE: 15.1825

Combination 20/72: {'sequence_length': 6, 'lstm_units': [64], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 74.82s | Train RMSE: 16.0762 | Test RMSE: 14.9722

Combination 21/72: {'sequence_length': 6, 'lstm_units': [64, 32], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 63.09s | Train RMSE: 18.9975 | Test RMSE: 15.0881

Combination 22/72: {'sequence_length': 6, 'lstm_units': [64, 32], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 75.63s | Train RMSE: 17.5252 | Test RMSE: 15.1467

Combination 23/72: {'sequence_length': 6, 'lstm_units': [64, 32], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 123.00s | Train RMSE: 15.9082 | Test RMSE: 15.1059

Combination 24/72: {'sequence_length': 6, 'lstm_units': [64, 32], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 83.15s | Train RMSE: 16.1202 | Test RMSE: 15.0795

Combination 25/72: {'sequence_length': 12, 'lstm_units': [8, 4], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 38.01s | Train RMSE: 21.4405 | Test RMSE: 19.1498

Combination 26/72: {'sequence_length': 12, 'lstm_units': [8, 4], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 41.71s | Train RMSE: 21.0093 | Test RMSE: 19.5017

Combination 27/72: {'sequence_length': 12, 'lstm_units': [8, 4], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 66.63s | Train RMSE: 16.9550 | Test RMSE: 15.3029

Combination 28/72: {'sequence_length': 12, 'lstm_units': [8, 4], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 58.54s | Train RMSE: 16.5904 | Test RMSE: 14.9444

Combination 29/72: {'sequence_length': 12, 'lstm_units': [16, 8], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 90.15s | Train RMSE: 21.9226 | Test RMSE: 14.9639

Combination 30/72: {'sequence_length': 12, 'lstm_units': [16, 8], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 121.67s | Train RMSE: 20.4780 | Test RMSE: 15.2646

Combination 31/72: {'sequence_length': 12, 'lstm_units': [16, 8], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 73.86s | Train RMSE: 16.6906 | Test RMSE: 15.0736

Combination 32/72: {'sequence_length': 12, 'lstm_units': [16, 8], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 93.79s | Train RMSE: 16.2482 | Test RMSE: 15.0010

Combination 33/72: {'sequence_length': 12, 'lstm_units': [128], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 73.91s | Train RMSE: 16.2687 | Test RMSE: 15.0673

Combination 34/72: {'sequence_length': 12, 'lstm_units': [128], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 37.58s | Train RMSE: 16.7630 | Test RMSE: 15.2031

Combination 35/72: {'sequence_length': 12, 'lstm_units': [128], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 52.03s | Train RMSE: 16.2312 | Test RMSE: 15.1555

Combination 36/72: {'sequence_length': 12, 'lstm_units': [128], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 52.09s | Train RMSE: 16.2750 | Test RMSE: 15.0772

Combination 37/72: {'sequence_length': 12, 'lstm_units': [32, 16], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 53.23s | Train RMSE: 18.0106 | Test RMSE: 15.1227

Combination 38/72: {'sequence_length': 12, 'lstm_units': [32, 16], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 81.80s | Train RMSE: 19.9816 | Test RMSE: 15.0442

Combination 39/72: {'sequence_length': 12, 'lstm_units': [32, 16], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 49.95s | Train RMSE: 16.4747 | Test RMSE: 14.9910

Combination 40/72: {'sequence_length': 12, 'lstm_units': [32, 16], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 61.74s | Train RMSE: 16.4789 | Test RMSE: 15.0448

Combination 41/72: {'sequence_length': 12, 'lstm_units': [64], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 68.45s | Train RMSE: 16.2627 | Test RMSE: 15.1396

Combination 42/72: {'sequence_length': 12, 'lstm_units': [64], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 38.07s | Train RMSE: 16.7906 | Test RMSE: 15.1012

Combination 43/72: {'sequence_length': 12, 'lstm_units': [64], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 37.90s | Train RMSE: 16.4720 | Test RMSE: 15.1082

Combination 44/72: {'sequence_length': 12, 'lstm_units': [64], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 33.10s | Train RMSE: 16.8694 | Test RMSE: 15.1930

Combination 45/72: {'sequence_length': 12, 'lstm_units': [64, 32], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 54.91s | Train RMSE: 18.5831 | Test RMSE: 15.0505

Combination 46/72: {'sequence_length': 12, 'lstm_units': [64, 32], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 51.25s | Train RMSE: 18.1514 | Test RMSE: 14.9896

Combination 47/72: {'sequence_length': 12, 'lstm_units': [64, 32], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 60.27s | Train RMSE: 16.3820 | Test RMSE: 15.0674

Combination 48/72: {'sequence_length': 12, 'lstm_units': [64, 32], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 89.79s | Train RMSE: 16.0855 | Test RMSE: 15.1262

Combination 49/72: {'sequence_length': 24, 'lstm_units': [8, 4], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 61.13s | Train RMSE: 21.6013 | Test RMSE: 19.3093

Combination 50/72: {'sequence_length': 24, 'lstm_units': [8, 4], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 123.17s | Train RMSE: 23.9988 | Test RMSE: 18.0352

Combination 51/72: {'sequence_length': 24, 'lstm_units': [8, 4], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 144.43s | Train RMSE: 16.5879 | Test RMSE: 15.9489

Combination 52/72: {'sequence_length': 24, 'lstm_units': [8, 4], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 72.51s | Train RMSE: 17.3095 | Test RMSE: 16.4142

Combination 53/72: {'sequence_length': 24, 'lstm_units': [16, 8], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 99.94s | Train RMSE: 24.6203 | Test RMSE: 15.7793

Combination 54/72: {'sequence_length': 24, 'lstm_units': [16, 8], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 44.43s | Train RMSE: 23.0344 | Test RMSE: 19.8680

Combination 55/72: {'sequence_length': 24, 'lstm_units': [16, 8], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 95.00s | Train RMSE: 16.5567 | Test RMSE: 15.1178

Combination 56/72: {'sequence_length': 24, 'lstm_units': [16, 8], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 161.33s | Train RMSE: 16.2672 | Test RMSE: 15.4291

Combination 57/72: {'sequence_length': 24, 'lstm_units': [128], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 98.71s | Train RMSE: 16.1545 | Test RMSE: 15.2459

Combination 58/72: {'sequence_length': 24, 'lstm_units': [128], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 55.46s | Train RMSE: 16.3032 | Test RMSE: 15.3423

Combination 59/72: {'sequence_length': 24, 'lstm_units': [128], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 65.27s | Train RMSE: 16.8691 | Test RMSE: 15.2185

Combination 60/72: {'sequence_length': 24, 'lstm_units': [128], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 71.51s | Train RMSE: 15.9102 | Test RMSE: 15.1734

Combination 61/72: {'sequence_length': 24, 'lstm_units': [32, 16], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 65.02s | Train RMSE: 20.3867 | Test RMSE: 16.5164

Combination 62/72: {'sequence_length': 24, 'lstm_units': [32, 16], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 99.21s | Train RMSE: 24.7159 | Test RMSE: 16.2643

Combination 63/72: {'sequence_length': 24, 'lstm_units': [32, 16], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 95.76s | Train RMSE: 16.2195 | Test RMSE: 15.2391

Combination 64/72: {'sequence_length': 24, 'lstm_units': [32, 16], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 90.37s | Train RMSE: 16.2131 | Test RMSE: 15.1713

Combination 65/72: {'sequence_length': 24, 'lstm_units': [64], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 91.61s | Train RMSE: 18.7988 | Test RMSE: 15.3702

Combination 66/72: {'sequence_length': 24, 'lstm_units': [64], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 68.75s | Train RMSE: 16.3162 | Test RMSE: 15.2598

Combination 67/72: {'sequence_length': 24, 'lstm_units': [64], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 99.97s | Train RMSE: 15.7341 | Test RMSE: 15.2479

Combination 68/72: {'sequence_length': 24, 'lstm_units': [64], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 85.66s | Train RMSE: 15.7833 | Test RMSE: 15.1525

Combination 69/72: {'sequence_length': 24, 'lstm_units': [64, 32], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 113.04s | Train RMSE: 21.6391 | Test RMSE: 15.1693

Combination 70/72: {'sequence_length': 24, 'lstm_units': [64, 32], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 78.47s | Train RMSE: 19.5873 | Test RMSE: 15.4163

Combination 71/72: {'sequence_length': 24, 'lstm_units': [64, 32], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 91.36s | Train RMSE: 16.1430 | Test RMSE: 15.2999

Combination 72/72: {'sequence_length': 24, 'lstm_units': [64, 32], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 56.30s | Train RMSE: 16.7632 | Test RMSE: 15.2155

In [ ]:
from google.colab import runtime
runtime.unassign()

In [ ]:
param_grid = {
    'sequence_length': [3],
    'lstm_units': [
        [8, 4],
        [16,8],
        [128],
        [32,16],
        [64],
        [64,32]
    ],
    'dropout_rate': [0.6, 0.1, 0],
    'learning_rate': [0.002, 0.004, 0.01],
    'batch_size': [32],
    'epochs': [40]
}

In [ ]:
df_results = lstm_grid_search(X_train, y_train_scaled, X_test, y_test, scaler_y, param_grid, 4)

Starting grid search: 54 combinations

Combination 1/54: {'sequence_length': 3, 'lstm_units': [8, 4], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 53.72s | Train RMSE: 21.3407 | Test RMSE: 17.5387

Combination 2/54: {'sequence_length': 3, 'lstm_units': [8, 4], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 40.61s | Train RMSE: 21.3800 | Test RMSE: 15.9510

Combination 3/54: {'sequence_length': 3, 'lstm_units': [8, 4], 'dropout_rate': 0.6, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 65.63s | Train RMSE: 22.2919 | Test RMSE: 17.6424

Combination 4/54: {'sequence_length': 3, 'lstm_units': [8, 4], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 98.29s | Train RMSE: 16.8569 | Test RMSE: 15.3952

Combination 5/54: {'sequence_length': 3, 'lstm_units': [8, 4], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 170.67s | Train RMSE: 16.8536 | Test RMSE: 15.0618

Combination 6/54: {'sequence_length': 3, 'lstm_units': [8, 4], 'dropout_rate': 0.1, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 106.14s | Train RMSE: 16.7946 | Test RMSE: 15.1630

Combination 7/54: {'sequence_length': 3, 'lstm_units': [8, 4], 'dropout_rate': 0, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 42.42s | Train RMSE: 16.7955 | Test RMSE: 15.2284

Combination 8/54: {'sequence_length': 3, 'lstm_units': [8, 4], 'dropout_rate': 0, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 218.71s | Train RMSE: 16.2377 | Test RMSE: 15.3105

Combination 9/54: {'sequence_length': 3, 'lstm_units': [8, 4], 'dropout_rate': 0, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 156.55s | Train RMSE: 16.0911 | Test RMSE: 15.4401

Combination 10/54: {'sequence_length': 3, 'lstm_units': [16, 8], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 45.54s | Train RMSE: 22.6356 | Test RMSE: 17.6651

Combination 11/54: {'sequence_length': 3, 'lstm_units': [16, 8], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 40.89s | Train RMSE: 22.5004 | Test RMSE: 17.7978

Combination 12/54: {'sequence_length': 3, 'lstm_units': [16, 8], 'dropout_rate': 0.6, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 88.77s | Train RMSE: 20.6094 | Test RMSE: 15.2014

Combination 13/54: {'sequence_length': 3, 'lstm_units': [16, 8], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 120.29s | Train RMSE: 16.5971 | Test RMSE: 15.2522

Combination 14/54: {'sequence_length': 3, 'lstm_units': [16, 8], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 94.91s | Train RMSE: 16.7913 | Test RMSE: 15.2690

Combination 15/54: {'sequence_length': 3, 'lstm_units': [16, 8], 'dropout_rate': 0.1, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 82.50s | Train RMSE: 16.6937 | Test RMSE: 15.2593

Combination 16/54: {'sequence_length': 3, 'lstm_units': [16, 8], 'dropout_rate': 0, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 158.34s | Train RMSE: 16.3615 | Test RMSE: 15.4485

Combination 17/54: {'sequence_length': 3, 'lstm_units': [16, 8], 'dropout_rate': 0, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 130.35s | Train RMSE: 16.0610 | Test RMSE: 15.3240

Combination 18/54: {'sequence_length': 3, 'lstm_units': [16, 8], 'dropout_rate': 0, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 105.28s | Train RMSE: 15.8365 | Test RMSE: 15.6091

Combination 19/54: {'sequence_length': 3, 'lstm_units': [128], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 66.00s | Train RMSE: 16.7006 | Test RMSE: 15.0977

Combination 20/54: {'sequence_length': 3, 'lstm_units': [128], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 130.55s | Train RMSE: 16.3249 | Test RMSE: 15.2959

Combination 21/54: {'sequence_length': 3, 'lstm_units': [128], 'dropout_rate': 0.6, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 101.62s | Train RMSE: 15.0424 | Test RMSE: 15.4931

Combination 22/54: {'sequence_length': 3, 'lstm_units': [128], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 66.62s | Train RMSE: 16.3519 | Test RMSE: 15.2428

Combination 23/54: {'sequence_length': 3, 'lstm_units': [128], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 67.08s | Train RMSE: 16.3150 | Test RMSE: 15.2162

Combination 24/54: {'sequence_length': 3, 'lstm_units': [128], 'dropout_rate': 0.1, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 74.58s | Train RMSE: 15.5766 | Test RMSE: 15.3181

Combination 25/54: {'sequence_length': 3, 'lstm_units': [128], 'dropout_rate': 0, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 118.83s | Train RMSE: 16.0566 | Test RMSE: 15.3065

Combination 26/54: {'sequence_length': 3, 'lstm_units': [128], 'dropout_rate': 0, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 67.31s | Train RMSE: 15.9376 | Test RMSE: 15.4413

Combination 27/54: {'sequence_length': 3, 'lstm_units': [128], 'dropout_rate': 0, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 79.78s | Train RMSE: 14.9719 | Test RMSE: 15.4315

Combination 28/54: {'sequence_length': 3, 'lstm_units': [32, 16], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 49.99s | Train RMSE: 19.2515 | Test RMSE: 15.4744

Combination 29/54: {'sequence_length': 3, 'lstm_units': [32, 16], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 44.74s | Train RMSE: 18.9421 | Test RMSE: 15.5427

Combination 30/54: {'sequence_length': 3, 'lstm_units': [32, 16], 'dropout_rate': 0.6, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 40.77s | Train RMSE: 24.9635 | Test RMSE: 16.0986

Combination 31/54: {'sequence_length': 3, 'lstm_units': [32, 16], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 151.47s | Train RMSE: 16.4309 | Test RMSE: 15.3803

Combination 32/54: {'sequence_length': 3, 'lstm_units': [32, 16], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 69.17s | Train RMSE: 16.7404 | Test RMSE: 15.2716

Combination 33/54: {'sequence_length': 3, 'lstm_units': [32, 16], 'dropout_rate': 0.1, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 133.81s | Train RMSE: 14.4630 | Test RMSE: 16.7130

Combination 34/54: {'sequence_length': 3, 'lstm_units': [32, 16], 'dropout_rate': 0, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 195.22s | Train RMSE: 15.9868 | Test RMSE: 15.3561

Combination 35/54: {'sequence_length': 3, 'lstm_units': [32, 16], 'dropout_rate': 0, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 81.59s | Train RMSE: 16.1922 | Test RMSE: 15.3864

Combination 36/54: {'sequence_length': 3, 'lstm_units': [32, 16], 'dropout_rate': 0, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 91.09s | Train RMSE: 16.2595 | Test RMSE: 15.5750

Combination 37/54: {'sequence_length': 3, 'lstm_units': [64], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 57.84s | Train RMSE: 16.8091 | Test RMSE: 15.0348

Combination 38/54: {'sequence_length': 3, 'lstm_units': [64], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 57.64s | Train RMSE: 16.8076 | Test RMSE: 15.0622

Combination 39/54: {'sequence_length': 3, 'lstm_units': [64], 'dropout_rate': 0.6, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 75.76s | Train RMSE: 16.7509 | Test RMSE: 15.0258

Combination 40/54: {'sequence_length': 3, 'lstm_units': [64], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 67.48s | Train RMSE: 16.4227 | Test RMSE: 15.3076

Combination 41/54: {'sequence_length': 3, 'lstm_units': [64], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 111.25s | Train RMSE: 14.6110 | Test RMSE: 15.6946

Combination 42/54: {'sequence_length': 3, 'lstm_units': [64], 'dropout_rate': 0.1, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 85.99s | Train RMSE: 15.0055 | Test RMSE: 15.4267

Combination 43/54: {'sequence_length': 3, 'lstm_units': [64], 'dropout_rate': 0, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 56.67s | Train RMSE: 16.3847 | Test RMSE: 15.6218

Combination 44/54: {'sequence_length': 3, 'lstm_units': [64], 'dropout_rate': 0, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 74.98s | Train RMSE: 15.8878 | Test RMSE: 15.5165

Combination 45/54: {'sequence_length': 3, 'lstm_units': [64], 'dropout_rate': 0, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 66.51s | Train RMSE: 15.7869 | Test RMSE: 15.0563

Combination 46/54: {'sequence_length': 3, 'lstm_units': [64, 32], 'dropout_rate': 0.6, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 39.08s | Train RMSE: 17.6922 | Test RMSE: 15.4321

Combination 47/54: {'sequence_length': 3, 'lstm_units': [64, 32], 'dropout_rate': 0.6, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 45.11s | Train RMSE: 18.3835 | Test RMSE: 15.2269

Combination 48/54: {'sequence_length': 3, 'lstm_units': [64, 32], 'dropout_rate': 0.6, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 93.74s | Train RMSE: 17.5855 | Test RMSE: 15.3357

Combination 49/54: {'sequence_length': 3, 'lstm_units': [64, 32], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 123.88s | Train RMSE: 16.2594 | Test RMSE: 15.2818

Combination 50/54: {'sequence_length': 3, 'lstm_units': [64, 32], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 122.61s | Train RMSE: 15.8173 | Test RMSE: 15.4358

Combination 51/54: {'sequence_length': 3, 'lstm_units': [64, 32], 'dropout_rate': 0.1, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 116.41s | Train RMSE: 14.3531 | Test RMSE: 16.0294

Combination 52/54: {'sequence_length': 3, 'lstm_units': [64, 32], 'dropout_rate': 0, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 136.78s | Train RMSE: 16.1048 | Test RMSE: 15.2731

Combination 53/54: {'sequence_length': 3, 'lstm_units': [64, 32], 'dropout_rate': 0, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 95.24s | Train RMSE: 15.4067 | Test RMSE: 15.5308

Combination 54/54: {'sequence_length': 3, 'lstm_units': [64, 32], 'dropout_rate': 0, 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 40}
   -> Time: 96.17s | Train RMSE: 13.8553 | Test RMSE: 15.8317

In [ ]:
from google.colab import runtime
runtime.unassign()

In [17]:
param_grid = {
    'sequence_length': [3, 6, 12, 24],
    'lstm_units': [
        [256]
    ],
    'dropout_rate': [0.2, 0.1, 0],
    'learning_rate': [0.002, 0.004, 0.005],
    'batch_size': [32],
    'epochs': [40]
}

In [18]:
df_results = lstm_grid_search(X_train, y_train_scaled, X_test, y_test, scaler_y, param_grid, 5)

Starting grid search: 36 combinations

Combination 1/36: {'sequence_length': 3, 'lstm_units': [256], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 89.98s | Train RMSE: 16.2766 | Test RMSE: 15.1413

Combination 2/36: {'sequence_length': 3, 'lstm_units': [256], 'dropout_rate': 0.2, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 54.83s | Train RMSE: 16.4714 | Test RMSE: 15.1774

Combination 3/36: {'sequence_length': 3, 'lstm_units': [256], 'dropout_rate': 0.2, 'learning_rate': 0.005, 'batch_size': 32, 'epochs': 40}
   -> Time: 67.56s | Train RMSE: 15.8789 | Test RMSE: 15.2576

Combination 4/36: {'sequence_length': 3, 'lstm_units': [256], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 76.84s | Train RMSE: 16.3760 | Test RMSE: 15.4397

Combination 5/36: {'sequence_length': 3, 'lstm_units': [256], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 91.55s | Train RMSE: 14.6347 | Test RMSE: 15.8135

Combination 6/36: {'sequence_length': 3, 'lstm_units': [256], 'dropout_rate': 0.1, 'learning_rate': 0.005, 'batch_size': 32, 'epochs': 40}
   -> Time: 71.32s | Train RMSE: 15.1596 | Test RMSE: 15.4584

Combination 7/36: {'sequence_length': 3, 'lstm_units': [256], 'dropout_rate': 0, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 81.75s | Train RMSE: 15.5412 | Test RMSE: 15.4217

Combination 8/36: {'sequence_length': 3, 'lstm_units': [256], 'dropout_rate': 0, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 60.33s | Train RMSE: 16.1302 | Test RMSE: 15.3498

Combination 9/36: {'sequence_length': 3, 'lstm_units': [256], 'dropout_rate': 0, 'learning_rate': 0.005, 'batch_size': 32, 'epochs': 40}
   -> Time: 54.68s | Train RMSE: 16.2636 | Test RMSE: 15.2302

Combination 10/36: {'sequence_length': 6, 'lstm_units': [256], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 77.02s | Train RMSE: 15.8864 | Test RMSE: 15.1284

Combination 11/36: {'sequence_length': 6, 'lstm_units': [256], 'dropout_rate': 0.2, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 73.32s | Train RMSE: 15.6389 | Test RMSE: 15.1577

Combination 12/36: {'sequence_length': 6, 'lstm_units': [256], 'dropout_rate': 0.2, 'learning_rate': 0.005, 'batch_size': 32, 'epochs': 40}
   -> Time: 68.98s | Train RMSE: 15.1339 | Test RMSE: 15.2058

Combination 13/36: {'sequence_length': 6, 'lstm_units': [256], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 83.22s | Train RMSE: 15.1830 | Test RMSE: 15.1956

Combination 14/36: {'sequence_length': 6, 'lstm_units': [256], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 49.89s | Train RMSE: 16.2824 | Test RMSE: 15.1091

Combination 15/36: {'sequence_length': 6, 'lstm_units': [256], 'dropout_rate': 0.1, 'learning_rate': 0.005, 'batch_size': 32, 'epochs': 40}
   -> Time: 54.53s | Train RMSE: 15.8099 | Test RMSE: 15.0830

Combination 16/36: {'sequence_length': 6, 'lstm_units': [256], 'dropout_rate': 0, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 61.54s | Train RMSE: 16.0807 | Test RMSE: 15.1855

Combination 17/36: {'sequence_length': 6, 'lstm_units': [256], 'dropout_rate': 0, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 50.77s | Train RMSE: 15.9523 | Test RMSE: 15.1211

Combination 18/36: {'sequence_length': 6, 'lstm_units': [256], 'dropout_rate': 0, 'learning_rate': 0.005, 'batch_size': 32, 'epochs': 40}
   -> Time: 50.47s | Train RMSE: 15.8178 | Test RMSE: 15.2023

Combination 19/36: {'sequence_length': 12, 'lstm_units': [256], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 55.96s | Train RMSE: 16.1658 | Test RMSE: 15.2056

Combination 20/36: {'sequence_length': 12, 'lstm_units': [256], 'dropout_rate': 0.2, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 55.15s | Train RMSE: 16.2360 | Test RMSE: 15.1420

Combination 21/36: {'sequence_length': 12, 'lstm_units': [256], 'dropout_rate': 0.2, 'learning_rate': 0.005, 'batch_size': 32, 'epochs': 40}
   -> Time: 50.15s | Train RMSE: 16.4076 | Test RMSE: 15.1075

Combination 22/36: {'sequence_length': 12, 'lstm_units': [256], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 60.94s | Train RMSE: 16.0925 | Test RMSE: 15.0822

Combination 23/36: {'sequence_length': 12, 'lstm_units': [256], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 67.04s | Train RMSE: 15.4291 | Test RMSE: 14.9638

Combination 24/36: {'sequence_length': 12, 'lstm_units': [256], 'dropout_rate': 0.1, 'learning_rate': 0.005, 'batch_size': 32, 'epochs': 40}
   -> Time: 49.20s | Train RMSE: 16.2940 | Test RMSE: 15.0194

Combination 25/36: {'sequence_length': 12, 'lstm_units': [256], 'dropout_rate': 0, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 43.58s | Train RMSE: 16.2823 | Test RMSE: 15.1960

Combination 26/36: {'sequence_length': 12, 'lstm_units': [256], 'dropout_rate': 0, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 44.15s | Train RMSE: 16.3684 | Test RMSE: 15.1987

Combination 27/36: {'sequence_length': 12, 'lstm_units': [256], 'dropout_rate': 0, 'learning_rate': 0.005, 'batch_size': 32, 'epochs': 40}
   -> Time: 43.91s | Train RMSE: 16.2217 | Test RMSE: 14.9494

Combination 28/36: {'sequence_length': 24, 'lstm_units': [256], 'dropout_rate': 0.2, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 54.17s | Train RMSE: 16.5972 | Test RMSE: 15.1323

Combination 29/36: {'sequence_length': 24, 'lstm_units': [256], 'dropout_rate': 0.2, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 89.84s | Train RMSE: 16.7095 | Test RMSE: 15.1477

Combination 30/36: {'sequence_length': 24, 'lstm_units': [256], 'dropout_rate': 0.2, 'learning_rate': 0.005, 'batch_size': 32, 'epochs': 40}
   -> Time: 99.63s | Train RMSE: 13.8679 | Test RMSE: 15.1401

Combination 31/36: {'sequence_length': 24, 'lstm_units': [256], 'dropout_rate': 0.1, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 62.63s | Train RMSE: 16.6525 | Test RMSE: 15.1941

Combination 32/36: {'sequence_length': 24, 'lstm_units': [256], 'dropout_rate': 0.1, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 93.00s | Train RMSE: 14.8505 | Test RMSE: 14.9826

Combination 33/36: {'sequence_length': 24, 'lstm_units': [256], 'dropout_rate': 0.1, 'learning_rate': 0.005, 'batch_size': 32, 'epochs': 40}
   -> Time: 51.54s | Train RMSE: 16.5306 | Test RMSE: 15.0619

Combination 34/36: {'sequence_length': 24, 'lstm_units': [256], 'dropout_rate': 0, 'learning_rate': 0.002, 'batch_size': 32, 'epochs': 40}
   -> Time: 59.71s | Train RMSE: 16.0101 | Test RMSE: 15.2867

Combination 35/36: {'sequence_length': 24, 'lstm_units': [256], 'dropout_rate': 0, 'learning_rate': 0.004, 'batch_size': 32, 'epochs': 40}
   -> Time: 55.86s | Train RMSE: 16.6239 | Test RMSE: 15.1357

Combination 36/36: {'sequence_length': 24, 'lstm_units': [256], 'dropout_rate': 0, 'learning_rate': 0.005, 'batch_size': 32, 'epochs': 40}
   -> Time: 46.71s | Train RMSE: 16.7895 | Test RMSE: 15.1791

In [19]:
from google.colab import runtime
runtime.unassign()

In [ ]:
time.sleep(5)  # give logs time to flush
os._exit(0)

In [ ]:
# Parameter Grid
param_grid = {
    'sequence_length': [24],
    'lstm_units': [[64, 32, 16], [128, 64, 32]],
    'dropout_rate': [0.2],
    'learning_rate': [0.001, 0.005, 0.01],
    'batch_size': [64],
    'epochs': [50]
}

In [ ]:
# Parameter Grid
param_grid = {
    'sequence_length': [36, 48, 72],
    'lstm_units': [[32], [64]],
    'dropout_rate': [0.3, 0.5],
    'learning_rate': [0.001],
    'batch_size': [64],
    'epochs': [30]
}

In [ ]:
param_grid = {
    'sequence_length': [36],  # Best performer
    'lstm_units': [[64]],     # Best architecture
    'dropout_rate': [0.4, 0.5, 0.6],  # Higher dropout to reduce overfitting
    'learning_rate': [0.0005, 0.001],  # Slightly lower LR
    'batch_size': [32],       # Smaller batch for better generalization
    'epochs': [25]            # Fewer epochs with early stopping
}

In [ ]:
param_grid = {
    # 1. SEQUENCE LENGTH (4 options)
    # Focus around the sweet spot but expand range
    'sequence_length': [24, 36, 48, 60],  # Add 60h for daily+weekly patterns

    # 2. ARCHITECTURE (3 options)
    # Focus on best performers only
    'lstm_units': [
        [32],      # Simpler for less overfitting
        [64],      # Current best performer
        [48]       # Sweet spot between 32 and 64
    ],

    # 3. DROPOUT STRATEGY (5 options)
    # CRITICAL: Address overfitting with higher dropout
    'dropout_rate': [0.4, 0.5, 0.6, 0.7, 0.8],  # Push dropout higher!

    # 4. LEARNING RATE (1 option - FIXED)
    # Fix at optimal value to reduce combinations
    'learning_rate': [0.0005],  # Sweet spot from your results

    # 5. BATCH SIZE (1 option - fixed)
    'batch_size': [32],  # Smaller batch for better generalization

    # 6. EPOCHS (1 option - fixed)
    'epochs': [40]  # Longer training with early stopping
}

In [ ]:
# Run Grid Search
results, best_params, best_score = lstm_grid_search(X_train, y_train_scaled, X_test, y_test, scaler_y, param_grid)

print(f"\nGrid search completed. Best RMSE: {best_score:.4f}")
print(f"Best parameters: {best_params}")

Starting grid search: 60 combinations

Combination 1/60: {'sequence_length': 24, 'lstm_units': [32], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
Progress: 1.7%
Epoch 1/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - loss: 0.2751 - mae: 0.3322 - val_loss: 0.1859 - val_mae: 0.1487 - learning_rate: 5.0000e-04
Epoch 2/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0979 - mae: 0.1731 - val_loss: 0.1746 - val_mae: 0.1194 - learning_rate: 5.0000e-04
Epoch 3/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0850 - mae: 0.1539 - val_loss: 0.1720 - val_mae: 0.1110 - learning_rate: 5.0000e-04
Epoch 4/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0798 - mae: 0.1433 - val_loss: 0.1707 - val_mae: 0.1143 - learning_rate: 5.0000e-04
Epoch 5/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0777 - mae: 0.1360 - val_loss: 0.1695 - val_mae: 0.1045 - learning_rate: 5.0000e-04
Epoch 6/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0746 - mae: 0.1323 - val_loss: 0.1682 - val_mae: 0.0986 - learning_rate: 5.0000e-04
Epoch 7/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0718 - mae: 0.1271 - val_loss: 0.1697 - val_mae: 0.1076 - learning_rate: 5.0000e-04
Epoch 8/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - loss: 0.0705 - mae: 0.1234 - val_loss: 0.1686 - val_mae: 0.0991 - learning_rate: 5.0000e-04
Epoch 9/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - loss: 0.0699 - mae: 0.1225 - val_loss: 0.1673 - val_mae: 0.0916 - learning_rate: 5.0000e-04
Epoch 10/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0691 - mae: 0.1197 - val_loss: 0.1672 - val_mae: 0.0887 - learning_rate: 5.0000e-04
Epoch 11/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0669 - mae: 0.1173 - val_loss: 0.1668 - val_mae: 0.0877 - learning_rate: 5.0000e-04
Epoch 12/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0664 - mae: 0.1156 - val_loss: 0.1671 - val_mae: 0.0907 - learning_rate: 5.0000e-04
Epoch 13/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0666 - mae: 0.1146 - val_loss: 0.1667 - val_mae: 0.0836 - learning_rate: 5.0000e-04
Epoch 14/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0667 - mae: 0.1131 - val_loss: 0.1673 - val_mae: 0.0823 - learning_rate: 5.0000e-04
Epoch 15/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0649 - mae: 0.1107 - val_loss: 0.1667 - val_mae: 0.0838 - learning_rate: 1.5000e-04
Epoch 16/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0643 - mae: 0.1093 - val_loss: 0.1667 - val_mae: 0.0828 - learning_rate: 1.5000e-04
Epoch 17/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0643 - mae: 0.1086 - val_loss: 0.1674 - val_mae: 0.0873 - learning_rate: 1.5000e-04
Epoch 18/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0633 - mae: 0.1066 - val_loss: 0.1669 - val_mae: 0.0846 - learning_rate: 1.5000e-04
Epoch 19/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0638 - mae: 0.1083 - val_loss: 0.1674 - val_mae: 0.0862 - learning_rate: 4.5000e-05
Epoch 20/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0637 - mae: 0.1081 - val_loss: 0.1675 - val_mae: 0.0861 - learning_rate: 4.5000e-05
Results - Train RMSE: 14.9951, Test RMSE: 24.4037, R2: 0.2447
New best model found!

Combination 2/60: {'sequence_length': 24, 'lstm_units': [32], 'dropout_rate': 0.5, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
Progress: 3.3%
Epoch 1/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - loss: 0.2643 - mae: 0.3313 - val_loss: 0.1851 - val_mae: 0.1531 - learning_rate: 5.0000e-04
Epoch 2/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.1043 - mae: 0.1825 - val_loss: 0.1804 - val_mae: 0.1432 - learning_rate: 5.0000e-04
Epoch 3/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0949 - mae: 0.1664 - val_loss: 0.1754 - val_mae: 0.1276 - learning_rate: 5.0000e-04
Epoch 4/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0871 - mae: 0.1556 - val_loss: 0.1719 - val_mae: 0.1134 - learning_rate: 5.0000e-04
Epoch 5/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0830 - mae: 0.1501 - val_loss: 0.1725 - val_mae: 0.1179 - learning_rate: 5.0000e-04
Epoch 6/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 17ms/step - loss: 0.0799 - mae: 0.1445 - val_loss: 0.1714 - val_mae: 0.1101 - learning_rate: 5.0000e-04
Epoch 7/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0769 - mae: 0.1397 - val_loss: 0.1695 - val_mae: 0.1034 - learning_rate: 5.0000e-04
Epoch 8/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0755 - mae: 0.1369 - val_loss: 0.1687 - val_mae: 0.1023 - learning_rate: 5.0000e-04
Epoch 9/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0750 - mae: 0.1341 - val_loss: 0.1681 - val_mae: 0.0959 - learning_rate: 5.0000e-04
Epoch 10/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0729 - mae: 0.1303 - val_loss: 0.1685 - val_mae: 0.1011 - learning_rate: 5.0000e-04
Epoch 11/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0736 - mae: 0.1292 - val_loss: 0.1677 - val_mae: 0.0998 - learning_rate: 5.0000e-04
Epoch 12/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0727 - mae: 0.1277 - val_loss: 0.1676 - val_mae: 0.1027 - learning_rate: 5.0000e-04
Epoch 13/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0713 - mae: 0.1266 - val_loss: 0.1688 - val_mae: 0.1039 - learning_rate: 5.0000e-04
Epoch 14/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0712 - mae: 0.1255 - val_loss: 0.1697 - val_mae: 0.1028 - learning_rate: 5.0000e-04
Epoch 15/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0683 - mae: 0.1214 - val_loss: 0.1705 - val_mae: 0.0979 - learning_rate: 5.0000e-04
Epoch 16/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0698 - mae: 0.1214 - val_loss: 0.1690 - val_mae: 0.0957 - learning_rate: 1.5000e-04
Epoch 17/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0682 - mae: 0.1192 - val_loss: 0.1694 - val_mae: 0.0963 - learning_rate: 1.5000e-04
Results - Train RMSE: 15.1663, Test RMSE: 24.4215, R2: 0.2436

Combination 3/60: {'sequence_length': 24, 'lstm_units': [32], 'dropout_rate': 0.6, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
Progress: 5.0%
Epoch 1/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 14s 17ms/step - loss: 0.3427 - mae: 0.3864 - val_loss: 0.1857 - val_mae: 0.1503 - learning_rate: 5.0000e-04
Epoch 2/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 17ms/step - loss: 0.1283 - mae: 0.2111 - val_loss: 0.1780 - val_mae: 0.1318 - learning_rate: 5.0000e-04
Epoch 3/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - loss: 0.1093 - mae: 0.1874 - val_loss: 0.1772 - val_mae: 0.1307 - learning_rate: 5.0000e-04
Epoch 4/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 15ms/step - loss: 0.1000 - mae: 0.1758 - val_loss: 0.1763 - val_mae: 0.1289 - learning_rate: 5.0000e-04
Epoch 5/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0923 - mae: 0.1648 - val_loss: 0.1734 - val_mae: 0.1185 - learning_rate: 5.0000e-04
Epoch 6/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0890 - mae: 0.1585 - val_loss: 0.1730 - val_mae: 0.1166 - learning_rate: 5.0000e-04
Epoch 7/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0861 - mae: 0.1540 - val_loss: 0.1702 - val_mae: 0.1061 - learning_rate: 5.0000e-04
Epoch 8/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0845 - mae: 0.1515 - val_loss: 0.1700 - val_mae: 0.1044 - learning_rate: 5.0000e-04
Epoch 9/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0789 - mae: 0.1443 - val_loss: 0.1694 - val_mae: 0.0964 - learning_rate: 5.0000e-04
Epoch 10/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0800 - mae: 0.1424 - val_loss: 0.1697 - val_mae: 0.0934 - learning_rate: 5.0000e-04
Epoch 11/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0776 - mae: 0.1384 - val_loss: 0.1688 - val_mae: 0.0907 - learning_rate: 5.0000e-04
Epoch 12/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0754 - mae: 0.1361 - val_loss: 0.1715 - val_mae: 0.0955 - learning_rate: 5.0000e-04
Epoch 13/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0750 - mae: 0.1337 - val_loss: 0.1747 - val_mae: 0.1000 - learning_rate: 5.0000e-04
Epoch 14/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0735 - mae: 0.1319 - val_loss: 0.1746 - val_mae: 0.1056 - learning_rate: 5.0000e-04
Epoch 15/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0731 - mae: 0.1291 - val_loss: 0.1764 - val_mae: 0.1115 - learning_rate: 1.5000e-04
Epoch 16/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0718 - mae: 0.1280 - val_loss: 0.1753 - val_mae: 0.1103 - learning_rate: 1.5000e-04
Results - Train RMSE: 15.5985, Test RMSE: 24.5282, R2: 0.2369

Combination 4/60: {'sequence_length': 24, 'lstm_units': [32], 'dropout_rate': 0.7, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
Progress: 6.7%
Epoch 1/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - loss: 0.3617 - mae: 0.4085 - val_loss: 0.2023 - val_mae: 0.1633 - learning_rate: 5.0000e-04
Epoch 2/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.1490 - mae: 0.2384 - val_loss: 0.1860 - val_mae: 0.1397 - learning_rate: 5.0000e-04
Epoch 3/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 13s 18ms/step - loss: 0.1266 - mae: 0.2104 - val_loss: 0.1816 - val_mae: 0.1318 - learning_rate: 5.0000e-04
Epoch 4/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.1142 - mae: 0.1958 - val_loss: 0.1782 - val_mae: 0.1204 - learning_rate: 5.0000e-04
Epoch 5/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.1095 - mae: 0.1889 - val_loss: 0.1755 - val_mae: 0.1142 - learning_rate: 5.0000e-04
Epoch 6/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.1040 - mae: 0.1781 - val_loss: 0.1764 - val_mae: 0.1154 - learning_rate: 5.0000e-04
Epoch 7/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0954 - mae: 0.1694 - val_loss: 0.1743 - val_mae: 0.1110 - learning_rate: 5.0000e-04
Epoch 8/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0979 - mae: 0.1694 - val_loss: 0.1762 - val_mae: 0.1152 - learning_rate: 5.0000e-04
Epoch 9/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 17ms/step - loss: 0.0930 - mae: 0.1635 - val_loss: 0.1793 - val_mae: 0.1227 - learning_rate: 5.0000e-04
Epoch 10/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - loss: 0.0889 - mae: 0.1597 - val_loss: 0.1779 - val_mae: 0.1211 - learning_rate: 5.0000e-04
Epoch 11/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0870 - mae: 0.1559 - val_loss: 0.1765 - val_mae: 0.1230 - learning_rate: 1.5000e-04
Epoch 12/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0873 - mae: 0.1530 - val_loss: 0.1771 - val_mae: 0.1220 - learning_rate: 1.5000e-04
Results - Train RMSE: 17.0688, Test RMSE: 24.5432, R2: 0.2360

Combination 5/60: {'sequence_length': 24, 'lstm_units': [32], 'dropout_rate': 0.8, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
Progress: 8.3%
Epoch 1/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 14s 17ms/step - loss: 0.3982 - mae: 0.4255 - val_loss: 0.2084 - val_mae: 0.1689 - learning_rate: 5.0000e-04
Epoch 2/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.1857 - mae: 0.2715 - val_loss: 0.1936 - val_mae: 0.1460 - learning_rate: 5.0000e-04
Epoch 3/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.1557 - mae: 0.2447 - val_loss: 0.1900 - val_mae: 0.1336 - learning_rate: 5.0000e-04
Epoch 4/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.1346 - mae: 0.2231 - val_loss: 0.1867 - val_mae: 0.1296 - learning_rate: 5.0000e-04
Epoch 5/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.1314 - mae: 0.2140 - val_loss: 0.1857 - val_mae: 0.1281 - learning_rate: 5.0000e-04
Epoch 6/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.1194 - mae: 0.2031 - val_loss: 0.1917 - val_mae: 0.1362 - learning_rate: 5.0000e-04
Epoch 7/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.1187 - mae: 0.1972 - val_loss: 0.1914 - val_mae: 0.1343 - learning_rate: 5.0000e-04
Epoch 8/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.1122 - mae: 0.1910 - val_loss: 0.1966 - val_mae: 0.1460 - learning_rate: 5.0000e-04
Epoch 9/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.1062 - mae: 0.1845 - val_loss: 0.1980 - val_mae: 0.1497 - learning_rate: 1.5000e-04
Epoch 10/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.1058 - mae: 0.1812 - val_loss: 0.2009 - val_mae: 0.1541 - learning_rate: 1.5000e-04
Results - Train RMSE: 18.9994, Test RMSE: 24.8978, R2: 0.2138

Combination 6/60: {'sequence_length': 24, 'lstm_units': [64], 'dropout_rate': 0.4, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
Progress: 10.0%
Epoch 1/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 14s 17ms/step - loss: 0.1716 - mae: 0.2487 - val_loss: 0.1773 - val_mae: 0.1259 - learning_rate: 5.0000e-04
Epoch 2/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0869 - mae: 0.1489 - val_loss: 0.1747 - val_mae: 0.1228 - learning_rate: 5.0000e-04
Epoch 3/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 17ms/step - loss: 0.0764 - mae: 0.1337 - val_loss: 0.1715 - val_mae: 0.1101 - learning_rate: 5.0000e-04
Epoch 4/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0731 - mae: 0.1255 - val_loss: 0.1700 - val_mae: 0.1060 - learning_rate: 5.0000e-04
Epoch 5/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0685 - mae: 0.1184 - val_loss: 0.1699 - val_mae: 0.1110 - learning_rate: 5.0000e-04
Epoch 6/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0681 - mae: 0.1167 - val_loss: 0.1689 - val_mae: 0.1096 - learning_rate: 5.0000e-04
Epoch 7/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0664 - mae: 0.1141 - val_loss: 0.1694 - val_mae: 0.1039 - learning_rate: 5.0000e-04
Epoch 8/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0650 - mae: 0.1108 - val_loss: 0.1677 - val_mae: 0.0981 - learning_rate: 5.0000e-04
Epoch 9/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0640 - mae: 0.1088 - val_loss: 0.1682 - val_mae: 0.1048 - learning_rate: 5.0000e-04
Epoch 10/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - loss: 0.0633 - mae: 0.1071 - val_loss: 0.1678 - val_mae: 0.1021 - learning_rate: 5.0000e-04
Epoch 11/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 13s 18ms/step - loss: 0.0634 - mae: 0.1081 - val_loss: 0.1666 - val_mae: 0.0946 - learning_rate: 5.0000e-04
Epoch 12/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - loss: 0.0626 - mae: 0.1057 - val_loss: 0.1665 - val_mae: 0.0894 - learning_rate: 5.0000e-04
Epoch 13/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - loss: 0.0611 - mae: 0.1044 - val_loss: 0.1673 - val_mae: 0.0985 - learning_rate: 5.0000e-04
Epoch 14/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 13s 18ms/step - loss: 0.0622 - mae: 0.1047 - val_loss: 0.1673 - val_mae: 0.1007 - learning_rate: 5.0000e-04
Epoch 15/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - loss: 0.0629 - mae: 0.1042 - val_loss: 0.1659 - val_mae: 0.0920 - learning_rate: 5.0000e-04
Epoch 16/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0609 - mae: 0.1016 - val_loss: 0.1664 - val_mae: 0.0889 - learning_rate: 5.0000e-04
Epoch 17/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0612 - mae: 0.1020 - val_loss: 0.1661 - val_mae: 0.0917 - learning_rate: 5.0000e-04
Epoch 18/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0610 - mae: 0.1005 - val_loss: 0.1663 - val_mae: 0.0830 - learning_rate: 5.0000e-04
Epoch 19/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0593 - mae: 0.0983 - val_loss: 0.1658 - val_mae: 0.0811 - learning_rate: 1.5000e-04
Epoch 20/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0593 - mae: 0.0970 - val_loss: 0.1654 - val_mae: 0.0830 - learning_rate: 1.5000e-04
Epoch 21/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 14s 19ms/step - loss: 0.0607 - mae: 0.0971 - val_loss: 0.1655 - val_mae: 0.0828 - learning_rate: 1.5000e-04
Epoch 22/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - loss: 0.0582 - mae: 0.0960 - val_loss: 0.1656 - val_mae: 0.0829 - learning_rate: 1.5000e-04
Epoch 23/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 17ms/step - loss: 0.0585 - mae: 0.0962 - val_loss: 0.1655 - val_mae: 0.0841 - learning_rate: 1.5000e-04
Epoch 24/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 13s 18ms/step - loss: 0.0592 - mae: 0.0964 - val_loss: 0.1657 - val_mae: 0.0799 - learning_rate: 4.5000e-05
Epoch 25/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 14s 19ms/step - loss: 0.0591 - mae: 0.0949 - val_loss: 0.1659 - val_mae: 0.0814 - learning_rate: 4.5000e-05
Results - Train RMSE: 14.5300, Test RMSE: 24.4222, R2: 0.2435

Combination 7/60: {'sequence_length': 24, 'lstm_units': [64], 'dropout_rate': 0.5, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}
Progress: 11.7%
Epoch 1/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - loss: 0.1849 - mae: 0.2630 - val_loss: 0.1819 - val_mae: 0.1411 - learning_rate: 5.0000e-04
Epoch 2/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0909 - mae: 0.1597 - val_loss: 0.1797 - val_mae: 0.1388 - learning_rate: 5.0000e-04
Epoch 3/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0808 - mae: 0.1441 - val_loss: 0.1733 - val_mae: 0.1188 - learning_rate: 5.0000e-04
Epoch 4/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0757 - mae: 0.1346 - val_loss: 0.1733 - val_mae: 0.1198 - learning_rate: 5.0000e-04
Epoch 5/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0732 - mae: 0.1303 - val_loss: 0.1704 - val_mae: 0.1141 - learning_rate: 5.0000e-04
Epoch 6/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0702 - mae: 0.1251 - val_loss: 0.1690 - val_mae: 0.1077 - learning_rate: 5.0000e-04
Epoch 7/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - loss: 0.0691 - mae: 0.1217 - val_loss: 0.1693 - val_mae: 0.1058 - learning_rate: 5.0000e-04
Epoch 8/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0668 - mae: 0.1181 - val_loss: 0.1695 - val_mae: 0.1091 - learning_rate: 5.0000e-04
Epoch 9/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0676 - mae: 0.1183 - val_loss: 0.1675 - val_mae: 0.1019 - learning_rate: 5.0000e-04
Epoch 10/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0655 - mae: 0.1148 - val_loss: 0.1682 - val_mae: 0.1007 - learning_rate: 5.0000e-04
Epoch 11/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0659 - mae: 0.1142 - val_loss: 0.1673 - val_mae: 0.0955 - learning_rate: 5.0000e-04
Epoch 12/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0659 - mae: 0.1131 - val_loss: 0.1668 - val_mae: 0.0918 - learning_rate: 5.0000e-04
Epoch 13/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0646 - mae: 0.1110 - val_loss: 0.1670 - val_mae: 0.0839 - learning_rate: 5.0000e-04
Epoch 14/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0639 - mae: 0.1104 - val_loss: 0.1670 - val_mae: 0.0885 - learning_rate: 5.0000e-04
Epoch 15/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0650 - mae: 0.1099 - val_loss: 0.1671 - val_mae: 0.0964 - learning_rate: 5.0000e-04
Epoch 16/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0630 - mae: 0.1073 - val_loss: 0.1662 - val_mae: 0.0820 - learning_rate: 1.5000e-04
Epoch 17/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0619 - mae: 0.1041 - val_loss: 0.1662 - val_mae: 0.0827 - learning_rate: 1.5000e-04
Epoch 18/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0613 - mae: 0.1048 - val_loss: 0.1660 - val_mae: 0.0822 - learning_rate: 1.5000e-04
Epoch 19/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0613 - mae: 0.1034 - val_loss: 0.1663 - val_mae: 0.0797 - learning_rate: 1.5000e-04
Epoch 20/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0612 - mae: 0.1024 - val_loss: 0.1661 - val_mae: 0.0782 - learning_rate: 1.5000e-04
Epoch 21/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0606 - mae: 0.1019 - val_loss: 0.1663 - val_mae: 0.0781 - learning_rate: 1.5000e-04
Epoch 22/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0615 - mae: 0.1020 - val_loss: 0.1668 - val_mae: 0.0812 - learning_rate: 4.5000e-05
Epoch 23/40
741/741 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - loss: 0.0606 - mae: 0.1015 - val_loss: 0.1666 - val_mae: 0.0806 - learning_rate: 4.5000e-05
Results - Train RMSE: 14.6035, Test RMSE: 24.4894, R2: 0.2394

Combination 8/60: {'sequence_length': 24, 'lstm_units': [64], 'dropout_rate': 0.6, 'learning_rate': 0.0005, 'batch_size': 32, 'epochs': 40}

In [ ]:
results_df = pd.DataFrame([r for r in results if 'error' not in r])
results_df.to_csv('lstm_arobust_long_grid_search_results.csv', index=False)
print(f"Results saved to lstm_grid_search_results.csv")

Results saved to lstm_grid_search_results.csv

In [ ]:
# Create sequences with best parameters
SEQUENCE_LENGTH = best_params['sequence_length']
X_seq_final, y_seq_final = create_sequences(X_train, y_train_scaled, SEQUENCE_LENGTH)

In [ ]:
# Build final model with best parameters
final_model = build_model(
    best_params['sequence_length'],
    X_seq_final.shape[2],
    best_params['lstm_units'],
    best_params['dropout_rate'],
    best_params['learning_rate']
)

In [ ]:
# Train on ALL training data (no validation split for final model)
# callbacks = [
#     EarlyStopping(monitor='loss', patience=20, restore_best_weights=True, verbose=1),
#     ReduceLROnPlateau(monitor='loss', factor=0.5, patience=10, min_lr=0.00001, verbose=1)
# ]

callbacks = [
    EarlyStopping(
        monitor='val_loss',
        patience=5,
        restore_best_weights=True,
        min_delta=0.0001
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.3,
        patience=3,
        min_lr=0.00001
    )
]

In [ ]:
final_history = final_model.fit(
    X_seq_final, y_seq_final,
    epochs=best_params['epochs'] + 20,  # Allow more epochs for final training
    batch_size=best_params['batch_size'],
    callbacks=callbacks,
    verbose=1
)

Epoch 1/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 19s 16ms/step - loss: 0.2073 - mae: 0.2709 - learning_rate: 5.0000e-04
Epoch 2/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.1152 - mae: 0.1663 - learning_rate: 5.0000e-04
Epoch 3/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 16s 17ms/step - loss: 0.1071 - mae: 0.1513 - learning_rate: 5.0000e-04
Epoch 4/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 16s 18ms/step - loss: 0.1010 - mae: 0.1423 - learning_rate: 5.0000e-04
Epoch 5/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 15s 17ms/step - loss: 0.0974 - mae: 0.1372 - learning_rate: 5.0000e-04
Epoch 6/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 18s 19ms/step - loss: 0.0974 - mae: 0.1349 - learning_rate: 5.0000e-04
Epoch 7/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 18s 20ms/step - loss: 0.0954 - mae: 0.1311 - learning_rate: 5.0000e-04
Epoch 8/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 16s 17ms/step - loss: 0.0922 - mae: 0.1267 - learning_rate: 5.0000e-04
Epoch 9/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 16s 17ms/step - loss: 0.0924 - mae: 0.1269 - learning_rate: 5.0000e-04
Epoch 10/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 17s 18ms/step - loss: 0.0901 - mae: 0.1239 - learning_rate: 5.0000e-04
Epoch 11/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 17s 18ms/step - loss: 0.0920 - mae: 0.1237 - learning_rate: 5.0000e-04
Epoch 12/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 16ms/step - loss: 0.0892 - mae: 0.1216 - learning_rate: 5.0000e-04
Epoch 13/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - loss: 0.0899 - mae: 0.1221 - learning_rate: 5.0000e-04
Epoch 14/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - loss: 0.0903 - mae: 0.1203 - learning_rate: 5.0000e-04
Epoch 15/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 16s 18ms/step - loss: 0.0894 - mae: 0.1185 - learning_rate: 5.0000e-04
Epoch 16/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - loss: 0.0886 - mae: 0.1190 - learning_rate: 5.0000e-04
Epoch 17/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - loss: 0.0878 - mae: 0.1162 - learning_rate: 5.0000e-04
Epoch 18/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - loss: 0.0872 - mae: 0.1158 - learning_rate: 5.0000e-04
Epoch 19/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 18s 19ms/step - loss: 0.0874 - mae: 0.1149 - learning_rate: 5.0000e-04
Epoch 20/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 17s 17ms/step - loss: 0.0868 - mae: 0.1145 - learning_rate: 5.0000e-04
Epoch 21/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0861 - mae: 0.1148 - learning_rate: 5.0000e-04
Epoch 22/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - loss: 0.0855 - mae: 0.1122 - learning_rate: 5.0000e-04
Epoch 23/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0861 - mae: 0.1124 - learning_rate: 5.0000e-04
Epoch 24/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0855 - mae: 0.1106 - learning_rate: 5.0000e-04
Epoch 25/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 18s 19ms/step - loss: 0.0846 - mae: 0.1109 - learning_rate: 5.0000e-04
Epoch 26/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 13s 14ms/step - loss: 0.0853 - mae: 0.1111 - learning_rate: 5.0000e-04
Epoch 27/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0848 - mae: 0.1098 - learning_rate: 5.0000e-04
Epoch 28/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0845 - mae: 0.1094 - learning_rate: 5.0000e-04
Epoch 29/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0840 - mae: 0.1082 - learning_rate: 5.0000e-04
Epoch 30/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 16s 17ms/step - loss: 0.0837 - mae: 0.1082 - learning_rate: 5.0000e-04
Epoch 31/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0842 - mae: 0.1077 - learning_rate: 5.0000e-04
Epoch 32/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 13s 14ms/step - loss: 0.0841 - mae: 0.1070 - learning_rate: 5.0000e-04
Epoch 33/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 13s 14ms/step - loss: 0.0838 - mae: 0.1070 - learning_rate: 5.0000e-04
Epoch 34/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 13s 14ms/step - loss: 0.0842 - mae: 0.1062 - learning_rate: 5.0000e-04
Epoch 35/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 13s 14ms/step - loss: 0.0828 - mae: 0.1053 - learning_rate: 5.0000e-04
Epoch 36/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 13s 14ms/step - loss: 0.0830 - mae: 0.1054 - learning_rate: 5.0000e-04
Epoch 37/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0840 - mae: 0.1048 - learning_rate: 5.0000e-04
Epoch 38/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 13s 14ms/step - loss: 0.0826 - mae: 0.1031 - learning_rate: 5.0000e-04
Epoch 39/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 16ms/step - loss: 0.0826 - mae: 0.1043 - learning_rate: 5.0000e-04
Epoch 40/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0828 - mae: 0.1039 - learning_rate: 5.0000e-04
Epoch 41/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0822 - mae: 0.1025 - learning_rate: 5.0000e-04
Epoch 42/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0814 - mae: 0.1019 - learning_rate: 5.0000e-04
Epoch 43/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0813 - mae: 0.1016 - learning_rate: 5.0000e-04
Epoch 44/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - loss: 0.0812 - mae: 0.1017 - learning_rate: 5.0000e-04
Epoch 45/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - loss: 0.0815 - mae: 0.1003 - learning_rate: 5.0000e-04
Epoch 46/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - loss: 0.0816 - mae: 0.0999 - learning_rate: 5.0000e-04
Epoch 47/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 16s 17ms/step - loss: 0.0809 - mae: 0.0995 - learning_rate: 5.0000e-04
Epoch 48/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - loss: 0.0812 - mae: 0.1006 - learning_rate: 5.0000e-04
Epoch 49/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - loss: 0.0803 - mae: 0.1002 - learning_rate: 5.0000e-04
Epoch 50/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0823 - mae: 0.1006 - learning_rate: 5.0000e-04
Epoch 51/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 13s 14ms/step - loss: 0.0812 - mae: 0.1000 - learning_rate: 5.0000e-04
Epoch 52/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 12s 13ms/step - loss: 0.0802 - mae: 0.0992 - learning_rate: 5.0000e-04
Epoch 53/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0809 - mae: 0.1002 - learning_rate: 5.0000e-04
Epoch 54/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 15s 17ms/step - loss: 0.0796 - mae: 0.0986 - learning_rate: 5.0000e-04
Epoch 55/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 13s 14ms/step - loss: 0.0798 - mae: 0.0978 - learning_rate: 5.0000e-04
Epoch 56/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 12s 13ms/step - loss: 0.0805 - mae: 0.0981 - learning_rate: 5.0000e-04
Epoch 57/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 13s 14ms/step - loss: 0.0803 - mae: 0.0978 - learning_rate: 5.0000e-04
Epoch 58/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0804 - mae: 0.0984 - learning_rate: 5.0000e-04
Epoch 59/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0800 - mae: 0.0982 - learning_rate: 5.0000e-04
Epoch 60/60
926/926 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - loss: 0.0801 - mae: 0.0981 - learning_rate: 5.0000e-04

In [ ]:
# Training evaluation (convert scaled targets back to original scale)
y_train_actual = scaler_y.inverse_transform(y_seq_final.reshape(-1, 1)).flatten()
final_train_metrics = evaluate_model(final_model, X_seq_final, y_train_actual, scaler_y)

# Test evaluation
X_test_seq, _ = create_sequences(X_test, y_test.flatten(), SEQUENCE_LENGTH)
y_test_actual = y_test[SEQUENCE_LENGTH:]
final_test_metrics = evaluate_model(final_model, X_test_seq, y_test_actual, scaler_y)

print(f"\nFinal Model Performance:")
print(f"TRAINING SET:")
print(f"  Train RMSE: {final_train_metrics['rmse']:.4f}")
print(f"  Train R2: {final_train_metrics['r2']:.4f}")
print(f"  Train MAE: {final_train_metrics['mae']:.4f}")
print(f"  Train MAPE: {final_train_metrics['mape']:.4f}")

print(f"\nTEST SET:")
print(f"  Test RMSE: {final_test_metrics['rmse']:.4f}")
print(f"  Test R2: {final_test_metrics['r2']:.4f}")
print(f"  Test MAE: {final_test_metrics['mae']:.4f}")
print(f"  Test MAPE: {final_test_metrics['mape']:.4f}")

print(f"\nOVERFITTING ANALYSIS:")
print(f"  RMSE Difference (Train - Test): {final_train_metrics['rmse'] - final_test_metrics['rmse']:.4f}")
print(f"  R2 Difference (Train - Test): {final_train_metrics['r2'] - final_test_metrics['r2']:.4f}")
print(f"  MAE Difference (Train - Test): {final_train_metrics['mae'] - final_test_metrics['mae']:.4f}")
print(f"  MAPE Difference (Train - Test): {final_train_metrics['mape'] - final_test_metrics['mape']:.4f}")

# Save final model
final_model.save('best_lstm_model.keras')
print("\nFinal model saved as 'best_lstm_model.keras'")

Final Model Performance:
TRAINING SET:
  Train RMSE: 20.6354
  Train R2: 0.7919
  Train MAE: 10.5227
  Train MAPE: 2.4391

TEST SET:
  Test RMSE: 25.9417
  Test R2: 0.1516
  Test MAE: 9.8446
  Test MAPE: 2.7461

OVERFITTING ANALYSIS:
  RMSE Difference (Train - Test): -5.3063
  R2 Difference (Train - Test): 0.6403
  MAE Difference (Train - Test): 0.6781
  MAPE Difference (Train - Test): -0.3070

Final model saved as 'best_lstm_model.keras'

: